### PR TITLE
Not able to cancel and change language due to overflow in search on s…

### LINKED ISSUE #3596: Not able to cancel and change language due to overflow in search on smaller screens
**Actual Behaviour**

Not able to cancel and change language due to overflow in search on smaller screens when user select two or three Options in search box because of this user can not cancel and change language 

**Expected Behaviour**

User can select any options and can also use cancel and change language options

**Steps to reproduce it**

1. Head over to https://susi.ai/
2. Inspect the screen for smaller screen width and click on search option and then select three or two options the you can not able to click on cancel and on change language option

**Screenshots of the issue**

SusiIssuError

**Would you like to work on the issue?**

 Yes

### PR DESCRIPTION
**Pull request by madhur1846**
…maller screens

Fixes #3596 

Changes: [Changed the width of link and instead of showing complete name of the dropdown link, showing only first 2 characters ]

Demo Link: https://github.com/fossasia/susi.ai/issues/3596

Screenshots of the change:  Screenshot 2020-10-01 at 11 59 08 AM

### CODE REVIEW

**Comment by pulkit1joshi** [comment]
Demo link must look like this : https://pr-3598-fossasia-susi-web-chat.surge.sh/

**Comment by madhur1846** [comment]
> Demo link must look like this : https://pr-3598-fossasia-susi-web-chat.surge.sh/

Hello sir, thanks for replying 
As this is my first contribution, i don't know how to create this link. Can you tell me how to create this link?

**Comment by pulkit1joshi** [comment]
> > Demo link must look like this : https://pr-3598-fossasia-susi-web-chat.surge.sh/
> 
> Hello sir, thanks for replying
> As this is my first contribution, i don't know how to create this link. Can you tell me how to create this link?

Sure. You may read about here here : https://github.com/fossasia/susi.ai/blob/master/docs/DEPLOY.md
Also make sure to read other important links over the main page.

**Comment by madhur1846** [comment]
> read othe



> > > Demo link must look like this : https://pr-3598-fossasia-susi-web-chat.surge.sh/
> > 
> > 
> > Hello sir, thanks for replying
> > As this is my first contribution, i don't know how to create this link. Can you tell me how to create this link?
> 
> Sure. You may read about here here : https://github.com/fossasia/susi.ai/blob/master/docs/DEPLOY.md
> Also make sure to read other important links over the main page.

hello sir, 
after the surge commad it shows this error

error : "you do not have permission to publish to susi.ai"
what should i do?

**Comment by pulkit1joshi** [comment]
> > read othe
> 
> > > > Demo link must look like this : https://pr-3598-fossasia-susi-web-chat.surge.sh/
> > > 
> > > 
> > > Hello sir, thanks for replying
> > > As this is my first contribution, i don't know how to create this link. Can you tell me how to create this link?
> > 
> > 
> > Sure. You may read about here here : https://github.com/fossasia/susi.ai/blob/master/docs/DEPLOY.md
> > Also make sure to read other important links over the main page.
> 
> hello sir,
> after the surge commad it shows this error
> 
> error : "you do not have permission to publish to susi.ai"
> what should i do?
> 
> Screenshot 2020-10-01 at 3 29 23 PM

Watch this for better understanding how to use surge to deploy at susi.ai : https://www.youtube.com/watch?v=Gvc0uz13U1M
Basically you are surging over the actual susi.ai however you need a new url.

**Comment by madhur1846** [comment]
> > > read othe
> > 
> > 
> > > > > Demo link must look like this : https://pr-3598-fossasia-susi-web-chat.surge.sh/
> > > > 
> > > > 
> > > > Hello sir, thanks for replying
> > > > As this is my first contribution, i don't know how to create this link. Can you tell me how to create this link?
> > > 
> > > 
> > > Sure. You may read about here here : https://github.com/fossasia/susi.ai/blob/master/docs/DEPLOY.md
> > > Also make sure to read other important links over the main page.
> > 
> > 
> > hello sir,
> > after the surge commad it shows this error
> > error : "you do not have permission to publish to susi.ai"
> > what should i do?
> > Screenshot 2020-10-01 at 3 29 23 PM
> 
> Watch this for better understanding how to use surge to deploy at susi.ai : https://www.youtube.com/watch?v=Gvc0uz13U1M
> Basically you are surging over the actual susi.ai however you need a new url.

how to creaet new url?

**Comment by madhur1846** [comment]
> > > read othe
> > 
> > 
> > > > > Demo link must look like this : https://pr-3598-fossasia-susi-web-chat.surge.sh/
> > > > 
> > > > 
> > > > Hello sir, thanks for replying
> > > > As this is my first contribution, i don't know how to create this link. Can you tell me how to create this link?
> > > 
> > > 
> > > Sure. You may read about here here : https://github.com/fossasia/susi.ai/blob/master/docs/DEPLOY.md
> > > Also make sure to read other important links over the main page.
> > 
> > 
> > hello sir,
> > after the surge commad it shows this error
> > error : "you do not have permission to publish to susi.ai"
> > what should i do?
> > Screenshot 2020-10-01 at 3 29 23 PM
> 
> Watch this for better understanding how to use surge to deploy at susi.ai : https://www.youtube.com/watch?v=Gvc0uz13U1M
> Basically you are surging over the actual susi.ai however you need a new url.

Is this correct?

Screenshot 2020-10-01 at 4 33 12 PM

**Review by Dilshaad21 — COMMENTED** [review]
Provide a demo link with your current changes in it.

**Pull request closed without merging**
