### PR TITLE
Enable checkbox Reviewed Skills by default

### LINKED ISSUE #2191: Enable the checkbox for `Show only Reviewed Skills` by default
**Actual Behaviour**

Currently, it is unchecked by default, which means we're shown All Skills by default.

**Expected Behaviour**

As discussed in the meeting, it should be checked by default.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2191

Changes: Enable checkbox Reviewed Skills by default

Demo Link: https://pr-2321-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by fragm3** [comment]
@harsh-jindal I agree partly, but we need persistent application. And only reviewed skills are of priority

**Comment by fragm3** [comment]
@akshatnitd I am reviewing skills daily as you said.

**Comment by akshatnitd** [comment]
Please finalise it by today.

**Comment by fragm3** [comment]
@akshatnitd The reviewed checkbox is enabled by default correctly in surge link

**Comment by akshatnitd** [comment]
It wasn't showing up when I reviewed.

**Pull request merged**
