### PR TITLE
Fix Search box color fix and dropdown view #2589

### LINKED ISSUE #2589: Search box color fix and dropdown view
The search box has the following issues:
* when activated the surrounding is blue. Expected: It should be the same slightly darker gray as the background of the button itself
Screenshot from 2019-07-16 11-34-44

* the dropdown menus of the filters and language choices should be below the button (same as user dropdowns and Amazon)
Screenshot from 2019-07-16 11-35-27

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2589

Changes: Fix Search box color fix and dropdown view

Demo Link: https://pr-2599-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 

Screenshot 2019-07-16 at 8 51 22 PM

Screenshot 2019-07-16 at 8 51 34 PM

### CODE REVIEW

**Comment by fragm3** [comment]
Working fine for me in localhost, idk whats causing this

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal decided to show globe:

Screenshot 2019-07-16 at 10 35 54 PM
Screenshot 2019-07-16 at 12 13 01 AM

**Comment by harsh-jindal** [comment]
@fragm3 Please make the changes suggested by @akshatnitd . Show `-` when no skill or language is selected in their respective drop downs.

**Comment by fragm3** [comment]
@harsh-jindal @akshatnitd done:
Screenshot 2019-07-16 at 11 52 56 PM

**Comment by akshatnitd** [comment]
The blue border issue is there with the Language dropdown too.

**Comment by fragm3** [comment]
@akshatnitd fixed

**Pull request merged**
