### PR TITLE
Create Skill: Add Slider button to offer choice of Open Source / Public Skill vs. Private Skill

### LINKED ISSUE #2763: Create Skill: Add Slider button to offer choice of Open Source / Public Skill vs. Private Skill
Let's prepare the option for Open Source/Public Skills vs. Private Skills. On the skill create page https://susi.ai/skillWizard:
* provide a slider button in the top form area "Open Source and Public Skill (pre-selected) to be switched "on"
* when switched off show "Private Skill"
* behind that show a question mark "?". Clicking on this shows the following text: "Open Source Skills will show in the public directory and are editable by everyone just like a Wikipedia article. Private skills are only editable by the creator/owner of the skill. They are not listed in the public directory and can currently only be used by the creator/owner."

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2763 #2787 

Demo Link: https://pr-2790-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-08-05 at 7 37 51 PM
Screenshot 2019-08-05 at 7 38 09 PM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@akshatnitd Shall I decrease the size of the image bubble because height of the text field and image height are not same ?

**Comment by harsh-jindal** [comment]
@akshatnitd Fixed.

**Comment by mariobehling** [comment]
Looking more into detail:

* On the left of the switch button show "Private Skill"
* On the right of the switch button show "Open Source / Public Skill"
* Make the chosen option in standard color, make the option currently not chosen a gray.

Screenshot from 2019-08-05 16-50-00

**Comment by mariobehling** [comment]
The image alignment looks good on the skill creator page, but see the screenshot from the bot page below. On smaller screens there is a slight overlap with the first box.

Screenshot from 2019-08-05 16-57-28

**Comment by harsh-jindal** [comment]
@mariobehling Done.
Screenshot 2019-08-05 at 9 00 01 PM
Screenshot 2019-08-05 at 9 00 10 PM

**Comment by akshatnitd** [comment]
Also, there is space for the images in the screenshot you sent, please put it the same row.

**Comment by harsh-jindal** [comment]
@akshatnitd Fixed

**Pull request merged**
