### PR TITLE
clear textbox

### PR DESCRIPTION
**Pull request by makoteq**
Fixes  https://github.com/fossasia/susi.ai/issues/3212

Changes: change message var after click send

Demo Link: https://pr-3268-fossasia-susi-web-chat.surge.sh

Screenshots of the change: in issue

### CODE REVIEW

**Comment by anishagg17** [comment]
Please close your previous pr related to same issue

**Comment by makoteq** [comment]
@Dilshaad21 @akshatnitd  
is it ok now?

**Comment by makoteq** [comment]
@akshatnitd  @anishagg17 @Dilshaad21 Now it shoud be ok

**Comment by makoteq** [comment]
@akshatnitd Sorry for problem but if that changes are not correct, please specify what's wrong

**Comment by makoteq** [comment]
@akshatnitd Is this ok?

**Comment by makoteq** [comment]
@anishagg17 @akshatnitd What about now?

**Pull request closed without merging**
