### PR TITLE
Fix Notification and Skill Description Bug

### LINKED ISSUE #2289: Fix all antd notification errors.
**Actual Behaviour**
Currently the appbar overlaps with the antd notification.

**Expected Behaviour**
Fix it.

**Steps to reproduce it**
Compare more than 2 skill versions.

**Screenshots of the issue**
Screenshot 2019-06-16 at 10 09 58 AM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2289, #2288

Demo Link: https://pr-2302-fossasia-susi-web-chat.surge.sh

Changes: 
Screenshot 2019-06-17 at 7 55 43 AM
Screenshot 2019-06-17 at 7 56 08 AM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@akshatnitd I have opened an issue https://github.com/fossasia/susi.ai/issues/2305. Will work on it after this gets merged. I will try to keep more or less the same UI provided by antd notification.
@akshatnitd @fragm3 Please review

**Comment by harsh-jindal** [comment]
@fragm3 I didn't get what you meant by the placeholder text.

**Comment by fragm3** [comment]
@harsh-jindal In the screenshot provided, the test example: `'<The question that should be ...>`

**Comment by akshatnitd** [comment]
@harsh-jindal Please finalise it by today.

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Fixed. Please review

**Pull request merged**
