### PR TITLE
Fix chatApp bugs #2711

### LINKED ISSUE #2711: Chat box: Corner too rounded, font too big, playing videos does not show screen entirely
The chat box has the following issues. Please help to solve them: 
1. The corners are too rounded compared to the other styles used on the page and the spacing to the left of the box is not consistent with other spacing of the page. Reduce the rounding and increase the spacing to the left of the box.
2. The menu bar font of the box is too big. Use the same size as the text on the top menu bar.
Screenshot from 2019-07-29 10-10-12

3. Clicking on "Play Shakira" on the top slider show the videos mostly hidden if there are previous interactions. Expected: It should show the video screen in its entirety.
Screenshot from 2019-07-29 10-10-27

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2711 

Changes: 
- [x] Now opening new youtube video shows completely
- [x] Fix UI

Demo Link: https://pr-2723-fossasia-susi-web-chat.surge.sh

Screenshot 2019-07-29 at 11 10 30 PM

### CODE REVIEW

**Comment by fragm3** [comment]
Will be fixing https://github.com/fossasia/susi.ai/issues/2718 as well in this

**Comment by fragm3** [comment]
@akshatnitd it is present, see carefully

**Comment by samagragupta** [comment]
I was already working on that. https://github.com/fossasia/susi.ai/issues/2718#issuecomment-515942484

Please close this.

**Comment by fragm3** [comment]
Sure, there are 2 PR's open, work on the issue your claimed

**Comment by harsh-jindal** [comment]
@fragm3 Opening the chat with video present previously does not show the video screen entirely. I have to scroll down to view the video.

**Comment by fragm3** [comment]
@harsh-jindal I didn't rebase the commits(due to samagra copying code), so the deployed link had older code. Check now

**Comment by harsh-jindal** [comment]
@fragm3 Still doesn't work for me. If i say play something, it scrolls down to the message bubble saying `playing something` and stops, instead it should go till the video chat bubble ends.

**Comment by fragm3** [comment]
@harsh-jindal yes, video takes time to load

**Comment by harsh-jindal** [comment]
@fragm3 3rd point of the issue is to solve the video not showing up entirely.

**Comment by fragm3** [comment]
@harsh-jindal yes, I know that. The thing is, it's working on my localhost but not on surge deployed link. I have rebased PR, let's see now

**Comment by fragm3** [comment]
@harsh-jindal @akshatnitd please test this PR on your localhost, not sure why changes not reflecting on surge.

**Comment by mariobehling** [comment]
Could you redeploy on surge please? Showing complete video is not working there still.

**Comment by fragm3** [comment]
@mariobehling I tried deploying it, tried to deploy 3 times, no changes being reflected on deployed. Whereas, working on localhost

However, I am attaching a GIF:
Jul-31-2019 22-25-02

**Comment by mariobehling** [comment]
Let's try if it works in the live deployment. Not, sure what is happening. Need to follow up otherwise. Thanks!

**Pull request merged**
