### PR TITLE
fix: burger menu icon shows up between 768px and  520 px 

### LINKED ISSUE #3594: Visibility of Burger Menu for width from 520px to 768px
**Actual Behaviour**
If we go for width less than 520px we have burger menu which works smooth.But for width range from 520px to 768px ,side bar disappears and there is no burger menu.

**Expected Behaviour**

It would be better if we can make burger menu visible for width ranges from 520px to 768px. 
**Steps to reproduce it**

1.After opening site ,go for inpect element and issue can be seen as shown:

**Screenshots of the issue**
for_width_morethan_768

pic2
pic3

**Would you like to work on the issue?**
Open for all!

### PR DESCRIPTION
**Pull request by naman360**
Fixes #3594 

Changes: Passed parameter as 768 to isMobileView function for getting burger menu icon to be displayed for screen width less than 768px.

Demo Link: https://pr-3600-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
**Before**
Initi
Here, No icon is present for screen width less than 768px.

**After**
Final
Here, menu icon is visible for screen width less than 768px.

### CODE REVIEW

**Comment by naman360** [comment]
@snitin315 Please review.

**Comment by naman360** [comment]
@snitin315 @iamareebjamal Review please?

**Comment by ksraj123** [comment]
This Fixes #3590 too.

**Comment by naman360** [comment]
@iamareebjamal @snitin315 Please review?

**Review by dheerajkotwani — APPROVED** [review]

**Review by akshatnitd — APPROVED** [review]

**Pull request merged**
