### PR TITLE
Unnecessary Password notification is removed(in login form)

### LINKED ISSUE #2704: Unnecessary notification below password in the Login Panel
**Actual Behaviour**
In the Login panel, below password, it show the error notification -"Password should be at least 6 to 64 characters",which is totally unnecessary because user have to input the exact password that he/she used during signup.

**Expected Behaviour**

The following password error notification should be removed 

**Screenshots of the issue**
pass_Comm

**Would you like to work on the issue?**
Yes ,i would like to work on it

### PR DESCRIPTION
**Pull request by tanujvyas10**
Fixes #2704 

Changes: **Unnecessary Password notification is removed(in login form)**

Demo Link:[http://debonair-ocean.surge.sh/](http://debonair-ocean.surge.sh/)
Screenshots of the change: [Add screenshots depicting the changes.]
login

### CODE REVIEW

**Comment by tanujvyas10** [comment]
@fragm3  and @harsh-jindal  I am not in using github. But i want to contribute ,hence , i am trying to do so.
@harsh-jindal   i have removed the previous PR changes but these commits are still coming.Please let me know , if these commits creating any trouble.The commits are only looking as a history record but the file change in only regarding the issue i fixed**(1 file change)** .So,if approved ,i do not think you will get any problem to accept the changes .I have made changes only regarding the login form.Please review my work.Thank you

**Comment by harsh-jindal** [comment]
@tanujvyas10 Do this:
1. `git checkout Password-notification`
2. `git fetch upstream`

If you do not have remote `upstream`:
`git checkout master`
`git remote add upstream https://github.com/fossasia/susi.ai.git`
Again come back to your branch where changes have been made by
`git checkout Password-notification`

3. `git rebase upstream/master` 

If you get merge conflicts:
Fix them in your editor.
Add the conflicted file.
then `git rebase --continue`

4. `git push -f origin Password-notification`

**Comment by tanujvyas10** [comment]
@harsh-jindal i performed all your instruction.Still the 3 commit history is still present.What to do sir?

**Comment by tanujvyas10** [comment]
@fragm3  and @harsh-jindal  Please reveiw my work.Thank you

**Comment by harsh-jindal** [comment]
@tanujvyas10 Did you clone the project from your fork?
You need to fork the project on the top right and copy that url and then create a repo `git clone url copied`

**Comment by tanujvyas10** [comment]
> @tanujvyas10 Did you clone the project from your fork?
> You need to fork the project on the top right and copy that url and then create a repo `git clone url copied`

i cloned the original susi.ai repo then made changes on my system,
 then i forked the original susi.ai repo , use ```git remote add local <url of the forked repo>``` 
made a branch and then commit then pushed and then created the PR

**Comment by harsh-jindal** [comment]
@tanujvyas10 You are suppose to do the opposite. 
clone the forked repo
`git add remote upstream original susi.ai repo`

**Comment by tanujvyas10** [comment]
> @tanujvyas10 You are suppose to do the opposite.
> clone the forked repo
> `git add remote upstream original susi.ai repo`

So ,do i have to re-create the PR from beginning?

**Comment by harsh-jindal** [comment]
@tanujvyas10 Yes. You can note down the changes you have made, so that shouldn't be an issue.

**Comment by tanujvyas10** [comment]
> @tanujvyas10 Yes. You can note down the changes you have made, so that shouldn't be an issue.

Can you please provide me the steps (starting from fork the repo), i should always follow whenever i will make a PR to any open source, I basically mean the github cmd commands for making a successful PR.Due to lack of github knowledge, i have already re-created the PR so many times from scratch.That will be a great help

**Comment by tanujvyas10** [comment]
You are right,i should have github knowledge first.

**Comment by fragm3** [comment]
Closing and reopening to check travis status

**Comment by akshatnitd** [comment]
@fragm3 It cannot be reopened. It says that the fork has been deleted.

**Comment by tanujvyas10** [comment]
I will recreate the PR

**Pull request closed without merging**
