### PR TITLE
Added language to the Installation Guides for SUSI.AI

### LINKED ISSUE #3311: Update Languages of Installation Files for SUSI.AI
**Actual Behaviour**
As of now the installation guides for SUSI.AI come in only a few languages. This makes it difficult for users to understand the various installation guides due to lack of fluency in available languages. 

**Expected Behaviour**
SUSI.AI should have all installation guides in various popular languages so that all people regardless of their language choices can use the guides provided.

**Steps to reproduce it**
1) Open the FOSSASIA SUSI.AI repository.
2) Navigate to the docs section in the repository.
3) On scrolling further we can the languages the installation guide is available in.

**Would you like to work on the issue?**
Yes.

### PR DESCRIPTION
**Pull request by aryanguls**
Fixes #3311 

Changes: For the purpose of this pull request I have added the installation guides in Thai language as well so as to start increasing the number of languages available to various users to read the installation guides.

Demo Link: Not required

Screenshots of the change: 
Screenshot (465)
Screenshot (466)
Screenshot (467)
Screenshot (468)

@mariobehling @hpdang @snitin315 Mentors please review.

### CODE REVIEW

**Comment by aryanguls** [comment]
@snitin315 Sir as the instructions are present in hindia, tamil, sinhala and bengal I feel that it should also be present in other important languages, particularly the important Asian languages. Could you please review?

**Comment by aryanguls** [comment]
@Dilshaad21 Sir I have passed all the checks. Please review and merge as soon as possible.

**Comment by Sid911** [comment]
I don't understand how are new languages being verified for doc etc. I think someone from the community knowing the language must verify this 😇

**Comment by aryanguls** [comment]
I have checked with my linguistics teacher who is fluent in thai, polish and russian but as russian is already added so i aksed her to help me with adding thai and polish. So she made te reuired changes and then I added it to the file.
She is a certified source

**Comment by aryanguls2** [comment]
Sir i have gotten it approved by someone who knows the language. But the issue is that the person approving the language is my linguistics teacher as I dont know anyone in the community who can help me. @akshatnitd

**Pull request closed without merging**
