### PR TITLE
Adding package-lock-json file

### PR DESCRIPTION
**Pull request by 26Vinayak**
#3591 
Changes: Adding package-lock-json for npm user

### CODE REVIEW

**Review by snitin315 — CHANGES_REQUESTED** [review]
No need. we have `yarn.lock` and only one package manager is used at a time.

**Comment by snitin315** [comment]
> #3591

The issue was to ignore it and not to add it. Please do read about `.gitignore`.

**Comment by 26Vinayak** [comment]
should i add package lock json to .gitignore ?

**Comment by snitin315** [comment]
Yes

**Review by elit-altum — CHANGES_REQUESTED** [review]
Please remove the commit for the ```package-lock.json``` file.

**Comment by akshatnitd** [comment]
Closing it. As the issue has been fixed.

**Pull request closed without merging**
