### PR TITLE
Fixes #1948: Reuse staticAppBar and Footer by creating a layout component [WIP]

### LINKED ISSUE #1948: Re-use Topbar instead of importing it in every component
**Actual Behaviour**

As of now the Topbar is being imported in every route

**Expected Behaviour**

Move the topbar out into the parent component and pass the routes as child components of topbar

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AakashMallik**
Fixes #1948 

Changes: The changes I have made are:
- [x] Reuse staticAppBar
- [ ] Reuse footer
- [ ] Reuse Topbar
- [ ] Reuse staticAppBar for Settings.react.js

Demo Link: https://pr-1960-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by AakashMallik** [comment]
@samagragupta Still WIP

**Comment by fragm3** [comment]
@AakashMallik how much time more for this PR? I want to proceed with Issue #1954

**Comment by AakashMallik** [comment]
> @AakashMallik how much time more for this PR? I want to proceed with Issue #1954

I am waiting for this https://github.com/fossasia/chat.susi.ai/pull/1994 to get merged. Dependent.

**Comment by akshatnitd** [comment]
Not required. Already implemented.

**Pull request closed without merging**
