### PR TITLE
Feature to Trim Email after Use

### LINKED ISSUE #3242: Email needs to be trimmed before signup,signin
**Expected Behaviour**

Email needs to be trimmed before signup,signin

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by aryanguls2**
Fixes #3242 

Changes: For the purpose of this pull request I have added the feature of trimming to various parts the website depending on when they become operational. I have added the trimming feature to only some of the times but in other cases due to security have not added them as in case of deleting the account or while resetting the password.

Demo Link: https://pr-3320-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]

@mariobehling @snitin315 @hpdang Mentors please review.

### CODE REVIEW

**Comment by aryanguls2** [comment]
@akshatnitd Sir I have made the change in the title and have also update the repository . Please merge as soon as possible. Sir could I also request you to kindly merge #3312 as well. I have verified it also and have update that branch as well.

**Comment by akshatnitd** [comment]
@aryanguls2 You have not squashed the commits.

**Comment by aryanguls2** [comment]
Sir I am unable to squash commits at the moment as my laptop is hanging continuously and is showing a lot of errors. Could you merge the request despite this ? Sorry for the inconvenience. @akshatnitd

**Comment by aryanguls2** [comment]
@akshatnitd Sir I have squashed the commits as well. Please accept this merge request as soon as possible.

**Pull request closed without merging**
