### PR TITLE
fix(share-susi-modal): aligned the modal items - I3527

### LINKED ISSUE #3527: Misaligned elements in share susi modal
**Actual Behaviour**

Currently the share susi modal has 
- Misaligned content-share button (Mozilla Firefox Developer Edition)
image

- Out of textarea scroll-bars (Google Chrome)
image

**Expected Behaviour**
The textarea and button styles should be fixed and coherent.

**Steps to reproduce it**
- Go to the chatbox and try to share a Susi response

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by elit-altum**
Fixes #3527 

Changes: 
- Center aligned items using flexbox
- Increased text area width and centered it.

Demo Link: https://pr-3536-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
image

### CODE REVIEW

**Comment by elit-altum** [comment]
@akshatnitd @snitin315
Please have a look!

**Comment by snitin315** [comment]
Can you share a screenshot in the mobile view?

**Comment by elit-altum** [comment]
Here you go @snitin315 !
image

**Comment by elit-altum** [comment]
@akshatnitd Could you please take a look at this?
Thank you!

**Pull request merged**
