### PR TITLE
enhanced styles of Cookie message Policy

### LINKED ISSUE #3482: change layout for cookie policy messege component.
**Actual Behaviour**

Currently the messege shows on bottom and takes too much unneccesary space.

Screenshot from 2020-02-16 12-04-02

**Expected Behaviour**

There is too much of blamk space below the text , which cany be utilised with a diiferent layout.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by arteevraina**
Fixes #3482 

Changes: added some styles to improve the layout.

DemoLink : https://pr-3531-fossasia-susi-web-chat.surge.sh/

Screenshots of the change:
image

Please review and suggest changes @snitin315 :)

### CODE REVIEW

**Comment by elit-altum** [comment]
@arteevraina Please add the link to the demo link for review!

**Comment by arteevraina** [comment]
@elit-altum Updated the PR with demo-link. Have a look!

**Comment by elit-altum** [comment]
image

This is causing issues on my screen.
Browser: Mozilla firefox developer edition
Display: 1920x1080

Please fix this!

**Comment by arteevraina** [comment]
@elit-altum Created a new PR #3542 for this. Please have a look!

**Pull request closed without merging**
