### PR TITLE
Fix remaining bugs and implement search bar in chat bubble

### LINKED ISSUE #2523: Fix remaining bugs and implement search bar in chat bubble
**Actual Behaviour**
Currently the chat bubble message section does not have search.

**Expected Behaviour**
Implement search and Click on the example in the speech bubble it should open in the chat box.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2523 

Changes: Added search bar
Demo Link: https://pr-2610-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-07-17 at 1 11 17 PM

### CODE REVIEW

**Comment by mariobehling** [comment]
* Instead of using "X" to close the chat icon show the magnifying glass in its place. The magnifying glass should be able to open and close a chat.
Screenshot from 2019-07-17 10-54-04
* Instead of red X keep it white
* Show 0/0 on the line of the search itself
* Use the full available width for the search
* There is a change on the language box. Should not happen.
Screenshot from 2019-07-17 10-59-40

**Comment by mariobehling** [comment]
Ok, I found it. What I identified as a white X is actually the forward arrow ">" of the slider.

Screenshot from 2019-07-17 11-15-33

Should be behind the chat box.

**Comment by samagragupta** [comment]
@mariobehling  https://github.com/fossasia/susi.ai/issues/2608

**Comment by harsh-jindal** [comment]
@mariobehling Made the changes . Please review. Also the language box change has occurred in the PR https://github.com/fossasia/susi.ai/pull/2607 made @fragm3 . But its merged and theres no effect of the bug on the susi.ai . I think this issue appears on surge link only maybe.

**Comment by harsh-jindal** [comment]
@akshatnitd This is how it will look. 
Screenshot 2019-07-17 at 8 30 33 PM
IMO it won't look that good as we need to display `0/0` next to it.
Shall I push the changes ?

**Comment by akshatnitd** [comment]
@harsh-jindal It would look good if we align everything properly. Put 0/0 in a grey box on right side as UI for  skill search type is made.

**Comment by harsh-jindal** [comment]
@akshatnitd Cool, making the changes now.

**Comment by harsh-jindal** [comment]
@akshatnitd Made the changes. Please review.
Screenshot 2019-07-17 at 9 38 07 PM

**Comment by harsh-jindal** [comment]
@samagragupta Which viewport? You have to reload the when you change to mobile view.

**Comment by harsh-jindal** [comment]
@fragm3 I have removed autoFocus when we click on search icon(which removes the blue outline). The blue outline was a result of chrome's user agent style sheet. I tried debugging it yesterday before pushing the changes for about 2 hours. But found no solution, even looked how you have done it.
About changing the UI. I guess its fine for now, I'll take this up later. As we should focus on more important issues for now.

**Comment by harsh-jindal** [comment]
@samagragupta Please tell the dimensions of the viewport because it appears fine for me.

**Comment by harsh-jindal** [comment]
@samagragupta Fixed

**Comment by harsh-jindal** [comment]
@samagragupta That is how the search is implemented. Also this is what whatsapp follows. You cannot search and type messages at the same time.

**Comment by samagragupta** [comment]
@harsh-jindal Then it looks fine to me.

**Pull request merged**
