### PR TITLE
Option to stop a skill playing audio #2614

### LINKED ISSUE #2614: Options to stop a skill, reduce the volume of playing music
When the web client uses the sound output, there is no way to stop the output. How could we achieve this and stop the sound output in regards to:
* stop music from playing
* stop reading out long articles

How to use the stop or pause command?

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2614

Changes: Stop currently playing audio from skill using 'stop', 'pause'  or 'abort' voice command

Demo Link: https://pr-2633-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by mariobehling** [comment]
@fragm3 I think we should follow the approach to use a hotword. What would be needed to make this possible on the webclient?

**Comment by fragm3** [comment]
@mariobehling definitely hotword approach could be used across the web client for more use cases like `okay susi` and it would open up a chat on the right side. But this approach will definitely take a longer time, I'll look into this in more details, if we find the relevant packages, this might be possible and would be a super amazing feature

**Comment by fragm3** [comment]
@akshatnitd But the problem here would be, to stop playing the audio, we would be first sending the response to the backend (how? using speech detection or typing), wait for the response, and then stop. This would result in a delay and be an additional overhead.

**Comment by akshatnitd** [comment]
Yes, I am aware of that. Check gitter channel for discussion. But it will help us implement cross platform solution

**Comment by fragm3** [comment]
@akshatnitd I am finished with skill chat audio stop, removed the global state to see if audio is playing as Orbiter said chat window should always be listening. Updated changes are in 2nd commit. If you give a heads up, I'll rebase

**Comment by fragm3** [comment]
@akshatnitd Hotword detection part needs more discussion. I need more details and what all we require, We need to follow a more structured approach of how to tackle big issues.

For this PR:
1. First commit only listens if susi speech is audio playing the message. 
2. Second commit always listens to user input as said by @Orbiter 

You can test it by typing `how to make biryani` and say stop.

**Comment by fragm3** [comment]
@akshatnitd done, 3rd commits does precisely 
Screenshot 2019-07-19 at 4 16 47 PM

**Comment by fragm3** [comment]
@akshatnitd fixed

**Comment by akshatnitd** [comment]
@fragm3 How do we pause the SoundCloud instances as well?
It should be done in this PR itself.

**Comment by fragm3** [comment]
@akshatnitd soundcloud already pausing, test it in deployed link

**Comment by akshatnitd** [comment]
@fragm3 Mention about this feature on the gitter channel. Good work.

**Pull request merged**
