### PR TITLE
Device Page: Add configuration options

### LINKED ISSUE #2488: Device Page: Add configuration options / settings
Please add the following options in the device page to configure local devices:
* [ ] tick box: Synchronize local skills with SUSI.AI skills database regularly. (default on)
   * [ ] button: Synchronize Now
* [ ] tick box: Synchronize (upload) private skills I create locally with my online account when online.
   * [ ] button: Upload Now
* [ ] button: "Link SUSI.AI account with device" when unlinked and show "Device linked to SUSI.AI account [user name here]" when linked plus a button "Unlink" - when people click this, then show a message "This will unlink your SUSI.AI local device from the SUSI.AI online account. You might loose data and configurations. Do you really want to proceed? Please type your username here."
* [ ] Section "Speech Recognition and Voice Output on Device"
    * [ ] For Speech Recognition (Speech to Text) use the service -> Add dropdown menu for Google, IBM Watson, etc.
   * [ ] For Voice Output (Text to Speech) use the service -> Add dropdown menu for Google, IBM Watson, etc.

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2488 

Changes: 
Clicking on the view icon i settings devices redirect to `/mydevices/:macId`

Demo Link: https://pr-2500-fossasia-susi-web-chat.surge.sh

Screenshots of the change:
Screenshot 2019-07-15 at 4 03 05 PM

Screenshot 2019-07-15 at 4 05 15 PM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@mariobehling Please check this. In the morning I got a bit confused. I was in the meeting and know that in the devices tab this shall be available on the local web client. Please review

**Comment by mariobehling** [comment]
I think we need to have a dedicated page for every device. So, on the overview device page there should be the table and map where several devices can be shown with an icon.

Screenshot from 2019-07-09 16-36-42

In the overview table, please add a "view" icon, in front of "edit" and "trash". The view icon then leads to a dedicated page to (susi.ai/mydevices/device[macaddresshere]. This page should be in the same style to the "dashboard pages" with different sections:
* All data shown in table
* The options as described in this issue
* A map showing the device on it

Screenshot from 2019-07-09 16-32-08

**Comment by mariobehling** [comment]
Also add "Speech" into the device page at susi.ai/mydevices/device[macaddresshere]

**Comment by harsh-jindal** [comment]
@mariobehling That sounds good. What should be present in current devices tab in settings ? Also on the overview page, where shall the table be placed , at the top after the gif or at the bottom. Shall I show the table only if devices are connected or have an option there itself to add devices.

**Comment by mariobehling** [comment]
We will come to "add device" options in another issue later. Just progress step by step and implement as described. We cannot go through all details in one issue.

**Comment by mariobehling** [comment]
> What should be present in current devices tab in settings ?

Please read the comments.

>> The view icon then leads to a dedicated page to (susi.ai/mydevices/device[macaddresshere]. This page should be in the same style to the "dashboard pages" with different sections:
* All data shown in table
* The options as described in this issue
* A map showing the device on it

**Comment by harsh-jindal** [comment]
Okay got it.

**Comment by harsh-jindal** [comment]
@mariobehling @akshatnitd @fragm3 Please review.

**Comment by mariobehling** [comment]
There should be an overview at https://susi.ai/mydevices and a tab in the dashboard, I think. Cannot find it.

**Comment by harsh-jindal** [comment]
@mariobehling I think a tab in the dashboard for `My devices` shall suffice. Because there we will display the same info on settings devices tab. So having another page `/mydevices` as overview is not required I think. I have added the each devices specific page. Please review that.
Adding a `My devices` section on dashboard. [Working on it now]

**Comment by mariobehling** [comment]
Screenshot from 2019-07-15 18-27-53

* Scroll bars on smaller screens should not be there
* Last column missing the heading "Actions"

**Comment by mariobehling** [comment]
@harsh-jindal I think a better way is porbably we just move the devices overview from "Settings" to the dashboard mydevices tab.

Then please delete the tab on the settings page "devices".

**Comment by harsh-jindal** [comment]
@mariobehling Done. Also the scrollbar appears if you use the tab or mobile view of the console. Will not be present on actual mobile and tab.

**Comment by mariobehling** [comment]
> @mariobehling Done. Also the scrollbar appears if you use the tab or mobile view of the console. Will not be present on actual mobile and tab.

Thanks. I don't know what you mean with the scroll bar. There should not be any internal scroll bar on the normal desktop view, which I am using here. Please get rid of it.

Screenshot from 2019-07-16 05-11-57

**Comment by harsh-jindal** [comment]
@mariobehling Fixed. Please review

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
