### PR TITLE
Bug fixes due to migration, Danger Zone, Delete Account

### LINKED ISSUE #2204: Fix Footer Links
**Actual Behaviour**

Due to migration, the link of footer not correct.

**Expected Behaviour**

Fix link of Footer

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2204,#2205,#2206,#2207

Changes: 
- Fix Footer Links
- Add missing links to staticAppBar
- Fix overview link, Shift CHAT_URL to newer URL
- Add Delete Account Modal
- Added Danger Zone

Screenshots
Screenshot 2019-06-06 at 8 11 14 PM
Screenshot 2019-06-06 at 8 11 28 PM
Screenshot 2019-06-06 at 8 22 39 PM

Demo Link: https://pr-2208-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@akshatnitd @fragm3 I think we can skip the delete account page and instead directly show the dialog asking user's password.

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal actually in the meeting mario said we need 2 confirmation for delete accounts. What do you suggest? 2 modal or should I remove one modal. Which one should I keep?

**Comment by mariobehling** [comment]
@akshatnitd Yes, I understand your point, but deleting a repo is different to deleting an account. I just want to be sure, people really know what they do. But: In the meeting we also said, we will check how Facebook and others do it. So, this is a good solution for the moment. Let's research more about this later.

**Comment by mariobehling** [comment]
I am merging this as a good step forward. Thanks and keep it up!

**Comment by fragm3** [comment]
That was close @mariobehling I just implemented a newer 2 dialog approach for it. Was about to push

**Pull request merged**
