### PR TITLE
Enhance search functionality #2473

### LINKED ISSUE #2473: Enhance search functionality
Please change the text in the search bar to "Search for Skills" instead of "Search".

Screenshot from 2019-07-06 19-15-30

Add filters as a drop down menu on the side within the search box with ticks:
* Search in
  * [ ] Names
  * [ ] Description
  * [ ] Examples
  * [ ] Code
  * [ ] Developers

Any other filter options that come to your mind?

Follow material UI but take inspiration from Amazon dropdown menu.

Screenshot from 2019-07-06 19-20-11

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2473

Changes: Enhance search functionality

Demo Link: https://pr-2478-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 

Screenshot 2019-07-07 at 3 34 52 AM

Screenshot 2019-07-11 at 7 51 37 PM

### CODE REVIEW

**Comment by fragm3** [comment]
@mariobehling should I proceed step by step with this issue, requires changes in the backend as well

**Comment by mariobehling** [comment]
Yes, you can solve it in several PRs. Also see the related issue here: https://github.com/fossasia/susi.ai/issues/2509

**Comment by mariobehling** [comment]
Not sure, why you need to wait so long for my answer. This issue is very important and should be finished. Just decide yourself in future if you want to develop things in one PR or several PRs.

**Comment by fragm3** [comment]
@mariobehling The PR is almost finalized. I am waiting for server-side changes to be reflected on the frontend, as server auto deploys new changes in few hours(PR merged today). Will finalise it by today itself, hoping server works fine.

**Comment by fragm3** [comment]
Except example search, everything working fine

**Comment by fragm3** [comment]
Let's continue discussion here: https://github.com/fossasia/susi.ai/issues/2522

**Pull request merged**
