### PR TITLE
Create getImage helper#2507, Popper position#2513

### LINKED ISSUE #2507: Create getImage helper function to fetch image from SUSI server folder
**Actual Behaviour**

Not present

**Expected Behaviour**

Create getImage helper function to fetch the image from SUSI server folder, using relative path

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2507, #2513

Changes: 
- [x] Popover margin on name hover
- [ ] Create getImage helper function to fetch the image from SUSI server folder

Demo Link: https://pr-2529-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 

Screenshot 2019-07-13 at 1 33 45 AM

### CODE REVIEW

**Comment by mariobehling** [comment]
1. The anonymous user icon is cut off on the top. Or is this a problem with the icon image?
2. There should be an image displayed. The user has uploaded an image in the settings. The user image is not shown.

**Comment by fragm3** [comment]
@mariobehling It is working fine for me, 

Screenshot 2019-07-13 at 2 58 40 AM

Upload an image from settings on surge link as well to see the changes

**Comment by mariobehling** [comment]
Ok, succeeded with upload of new photo, but top is slighly cut off still also in different resolutions tested on Chrome/Chromium.

Screenshot from 2019-07-12 23-54-17

**Comment by fragm3** [comment]
@mariobehling we are using Material UI component for it. Here we are restricted for constant image ratio and which portion to cut. Can't do anything about this issue

**Comment by mariobehling** [comment]
Let's get back to this later then and try to find a solution later. Thanks

**Pull request merged**
