### PR TITLE
Fixes #2338: Aligned Loading container in settings/devices 

### LINKED ISSUE #2338: Fix position of loader
**Actual Behaviour**

The loader is not at the centre

**Expected Behaviour**

Loader should be at the centre of the page.

**Screenshots of the issue**

Capture
Capture1

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by Dilshaad21**
Fixes #2338 

Changes: This PR is to align the loading container properly in the center of the devices in the settings section. The loading comes just after the circular loading container is loaded.The Screenshot of the Circular Loading which comes before the Loading container of GoogleApiwrapper is shown below.

Screenshot from 2019-06-24 14-56-55

Before changes being applied to the loading container

Demo Link: https://pr-[ADD_PULL_REQUEST_NUMBER_HERE]-fossasia-susi-web-chat.surge.sh

After changes being made ..
Screenshot from 2019-06-23 15-06-52

### CODE REVIEW

**Comment by Dilshaad21** [comment]
@samagragupta I haven't deleted it .I think some new lines got added when I ran yarn install.

**Comment by Dilshaad21** [comment]
@fragm3 I have put it in the gitignore file

**Comment by Dilshaad21** [comment]
@fragm3 The issue is not arising from the circularLoader. It's coming from the DefaultLoadingContainer which is by default there in the GoogleApiwrapper. So I had to create a Loading container exclusively in the index.js file of the devices tab to overwrite the default loading container of GoogleApiwrapper as I cannot directly alter it as it's present in the node_modules.

**Comment by Dilshaad21** [comment]
I have sqashed and made a new PR #2368

**Comment by akshatnitd** [comment]
Duplicate PR. Hence, closing.

**Pull request closed without merging**
