### PR TITLE
Preview Chat is now showing up correctly. fixes(#3629)

### LINKED ISSUE #3629: Preview chat not showing up correctly in create skill page
**Actual Behaviour**

The upper part of the chatbox in create skill/bot page is getting cut from the top.

**Expected Behaviour**

It should be aligned properly with the top margin.

**Steps to reproduce it**

1. Log in to your account.
2. Go to Create Skill/ Bot from the top navbar.
3. The preview chat will be opened at the right side.

**Screenshots of the issue**

Screenshot from 2020-12-27 16-23-02

**Would you like to work on the issue?**

No, it's free to pick

### PR DESCRIPTION
**Pull request by ashutoshc8101**
Fixes #3629 

Changes: 
  - Preview Chat is now showing correctly.

Demo Link: https://pr-3630-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
Capture

### CODE REVIEW

**Comment by ashutoshc8101** [comment]
@akshatnitd @Dilshaad21  Please review.

**Review by Dilshaad21 — CHANGES_REQUESTED** [review]
Also, bring up the susi.ai chat icon which is going beyond the bottom screen

**Comment by ashutoshc8101** [comment]
@Dilshaad21 I have performed the required changes. Now chat icon button is displayed as expected.

**Comment by ashutoshc8101** [comment]
@akshatnitd Please review.

**Review by akshatnitd — COMMENTED** [review]
Please fix the Travis failure

**Comment by ashutoshc8101** [comment]
@akshatnitd The travis failure is due to SURGE API TOKEN not being accepted at surge servers. I don't think, I can help in that case as I don't have access to surge service.

**Comment by ashutoshc8101** [comment]
@akshatnitd Please review. The build is passing now. The issue was with the surge. I removed the surge deployment.
Instead, I deployed my previewFix branch of the forked repository on vercel.

🔍 Inspect: [https://vercel.com/ashutoshc8101/susi-ai/gld8n2c57](https://vercel.com/ashutoshc8101/susi-ai/gld8n2c57)  
✅ Preview: [https://susi-ai-git-previewfix.ashutoshc8101.vercel.app](https://susi-ai-git-previewfix.ashutoshc8101.vercel.app)

**Pull request closed without merging**
