### PR TITLE
the menu that pops on hovering on "?" is completely inside the display console

### LINKED ISSUE #2671: menu under "?" is not completely inside the screen
**Actual Behaviour**
menu that pops by hovering on "?" is not completely inside the screen 
susi1
**Expected Behaviour**
menu should be completely inside the the screen

**Would you like to work on the issue?**
Yes , i would like to work on it

### PR DESCRIPTION
**Pull request by tanujvyas10**
Fixes #2671

**Changes: Now the menu that pops on hovering on "?" is completely inside the display console**
**Demo link**:
[https://nifty-sign.surge.sh](https://nifty-sign.surge.sh)

Screenshots of the change: [Add screenshots depicting the changes.]
**before the bug removing the menu use to look  like**
susi1

**After bug removing**
susi3

### CODE REVIEW

**Comment by tanujvyas10** [comment]
@fragm3  hello,sir ,i cannot able to squash the commits ,i request you to consider my latest commits i.e 
 **Fixed #2671 with few changes**  and you may ignore all before this commit and please review my work .Thank you

**Comment by fragm3** [comment]
@tanujvyas10 For rebasing, use `git rebase -i HEAD~n` --> n is the number of commits you want to rebase, this number can be found from the commits tab of your PR. The `Merge branch 'master' of https://github.com/tanujvyas10/susi.ai` commits work differently, those commits are not counted and may cause problems while rebasing. The approach I follow: push changes, and rebase according to the commits, using `git rebase -i HEAD~n`.

If suppose you have conflicts in your file, you need to update your master, and checkout on your current branch and do `git rebase -i upstream/master`, solve conflicts if any. This will make sure, you are updated.

Create a new PR, with your changes if you are unable to rebase it.

**Comment by tanujvyas10** [comment]
@fragm3 i already try to make a new PR but all the commits are also coming alot with it.

**Comment by tanujvyas10** [comment]
@samagragupta  , the surge deploy link is available now
[https://nifty-sign.surge.sh](https://nifty-sign.surge.sh)

**Comment by fragm3** [comment]
@tanujvyas10 You can see your fork changes from here: https://github.com/tanujvyas10/susi.ai

I would suggest you delete your fork, fork again and work on branches. Do not work on your master branch, create a new branch for separate PR. Always keep your master updated with remote(original susi.ai)

**Pull request closed without merging**
