### PR TITLE
The burger menu shows up as soon as the sidebar disappears #3594

### LINKED ISSUE #3594: Visibility of Burger Menu for width from 520px to 768px
**Actual Behaviour**
If we go for width less than 520px we have burger menu which works smooth.But for width range from 520px to 768px ,side bar disappears and there is no burger menu.

**Expected Behaviour**

It would be better if we can make burger menu visible for width ranges from 520px to 768px. 
**Steps to reproduce it**

1.After opening site ,go for inpect element and issue can be seen as shown:

**Screenshots of the issue**
for_width_morethan_768

pic2
pic3

**Would you like to work on the issue?**
Open for all!

### PR DESCRIPTION
**Pull request by padmaja-12**
Fixes #3594 

Changes: Earlier the sidebar was disappearing at width less than 770 and the burger menu was showing at less than or equal to 520.But now the burgermenu is showing as soon as the sidebar disappears. 

Demo Link: https://pr-3595-fossasia-susi-web-chat.surge.sh

Screenshots of the change:more than 768px
image
less than 768px
image

### CODE REVIEW

**Review by neeraj-2 — COMMENTED** [review]
Why did u change package-lock.json file

**Comment by padmaja-12** [comment]
apne pc pr setup krne k liye npm i ka command daale to depencies mein change ho gya

**Comment by snitin315** [comment]
Use yarn instead of npm as mentioned in README

**Comment by padmaja-12** [comment]
i have used yarn now....hope there is no further problem .

**Review by mohitm15 — APPROVED** [review]

**Comment by akshatnitd** [comment]
Issue is already fixed.

**Pull request closed without merging**
