### PR TITLE
Added space in the button text

### LINKED ISSUE #3398: Add space in the button text
**Actual Behaviour**
Currently, there is no space in the button text `SaveChanges`.

**Expected Behaviour**
There should be space present between the text.

**LogCat for the issue**

**Screenshots of the issue**

Screenshot from 2020-01-28 18-31-01

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Dishebh**
Fixes #3398 

Changes: Added space in button text between `SaveChanges`

Demo Link: https://pr-3393-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot from 2020-01-26 20-25-51

### CODE REVIEW

**Comment by anishagg17** [comment]
Please  mention issue number

**Comment by Dishebh** [comment]
@anishagg17 since it was a minor change / fix, I did not open the issue for
it.






Regards
Dishebh Bhayana

**Comment by Dishebh** [comment]
> LGTM
> Just write the issue number.

@samagragupta I did raise any issue for it as for the reason I mentioned above. So, that's why I left the issue no portion in the description as it is. 
Thanks for reviewing!

**Comment by akshatnitd** [comment]
@Dishebh Please open an issue for it and link it here.

**Comment by Dishebh** [comment]
@akshatnitd Done. Kindly review.

**Pull request merged**
