### PR TITLE
Fix search in chat

### LINKED ISSUE #2290: Fix search in chat
**Actual Behaviour**
Currently when we search anything on chat and use the arrows to highlight different instances, the page becomes blank(crashes) on when we use the down arrow and reach the last instance. 

**Expected Behaviour**
Fix it.

**Steps to reproduce it**
Go to susi.si/chat
Search anything.
Keep clicking on the down arrow.

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2290 

Changes: Now there is no error if one searches something and clicks on the down arrow for one complete iteration.
Demo Link: https://pr-2316-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@fragm3 updated surge link.

**Comment by harsh-jindal** [comment]
@fragm3 Fixed.

**Comment by harsh-jindal** [comment]
@fragm3 Works fine for me. 
@akshatnitd Can you confirm do you have the same issue?

**Comment by fragm3** [comment]
@akshatnitd yes got same errors

**Comment by harsh-jindal** [comment]
@akshatnitd @fragm3 fixed. Please review

**Comment by harsh-jindal** [comment]
@fragm3 Can you specify what is not working ?
I have fixed the following:
1. Search and functionality of up and down arrows.
2. Login on the chat page, which then loads in your logged in chat history.
3. Login while searching in logged off state, which then again loads your logged in chat history.

**Comment by harsh-jindal** [comment]
@akshatnitd @fragm3 Fixed.
`In logged out state, although the up and down arrow works, but the highlighting corresponding to the count (eg - 1/3) is incorrect.` 
This is was working fine for me before also.
Shubham can you confirm do you have the same error?

**Comment by fragm3** [comment]
The search functionality is still not fixed completely in this pr, I'll pick this up in further pr

**Pull request merged**
