### PR TITLE
Admin Dashboard Skills Tabs: Make subtabs uniform #2709

### LINKED ISSUE #2709: Make Admin Dashboard subtabs uniform, use material-table
The skills tabs "Deleted" and "Reported" at https://susi.ai/admin/skills are not following the same structure as the previous tabs. Please add missing columns and follow the same design and structure for all tabs in admin panel, use material-table

Screenshot from 2019-07-29 09-47-40

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2709

Changes: 
- [x] Added more metadata to the reported skills tab
- [x] Add more data to delete skills tab

Demo Link: https://pr-2756-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]

### CODE REVIEW

**Comment by mariobehling** [comment]
Bots page not following standard yet. Gray area missing. Please also check other pages.

Screenshot from 2019-08-01 00-04-19

**Comment by mariobehling** [comment]
Expected is, that all pages follow the skills page design.

Screenshot from 2019-08-01 00-05-50

**Comment by fragm3** [comment]
Okay, working on it

**Comment by fragm3** [comment]
@mariobehling I have updated the issue description: https://github.com/fossasia/susi.ai/issues/2709

**Comment by mariobehling** [comment]
* Please try to make the column width consistent across tabs.
* Last column cut off on "Reported" tab
Screenshot from 2019-08-01 00-05-50

**Comment by fragm3** [comment]
@mariobehling,
for point 1: I am using the same column config of active skill tabs
for point 2: This is a limitation we have to deal with

**Comment by fragm3** [comment]
@akshatnitd The skillToBedeleted api which shows deleted skills is giving 500 after I tried to get metadata. Giving array out of bound exception

**Comment by fragm3** [comment]
@akshatnitd I am looking into delete skill metadata issue, this PR is done from frontend side.

**Pull request merged**
