### PR TITLE
Substitute dropdown menu by "Login" and "Name with dropdown arrow" when logged in

### LINKED ISSUE #2425: Substitute dropdown menu by "Login" and "Name with dropdown arrow" when logged in
Please make the following changes:
* When user is not logged in show "Login" on the top right instead of the burger menu
* When the user is logged in show the name of the user and an arrow. Follow the same concept as Eventyay, please

Screenshot from 2019-07-03 00-13-18

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2425

Changes: 
- Substitute dropdown menu by "Login" and "Name with dropdown arrow" when logged in
- made a dropdown on the (?) symbol on the menu and showed "Support" and "About" 

Demo Link: https://pr-2482-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Capture
Capture

### CODE REVIEW

**Comment by samagragupta** [comment]
@harsh-jindal Removed the login icon.
And I don't think to make it in one line would look good. As in your account username is being displayed but may be in others it would be their's email id.

**Comment by harsh-jindal** [comment]
@samagragupta by making it one line I mean first the profile photo and then the username/email (i.e. like how it is currently don't change the UI just add the menu).

**Comment by samagragupta** [comment]
@akshatnitd Added the down arrow

**Comment by samagragupta** [comment]
@fragm3 I got confused as it was rendering properly in my system
Capture

**Comment by samagragupta** [comment]
@fragm3 Made the changes

**Comment by mariobehling** [comment]
Gray overlay not matching blue area. Please compare chat and skills in the same area.

Screenshot from 2019-07-10 09-15-51

Above "Settings" in the menu itself, please also add the dashboard in the menu.

**Comment by samagragupta** [comment]
@mariobehling Made the changes

**Comment by samagragupta** [comment]
Capture

**Comment by mariobehling** [comment]
Thanks.

**Pull request merged**
