### PR TITLE
Footer on support page made responsive

### LINKED ISSUE #3561: Un-responsive footer on support page
**Actual Behaviour**
On the support page the footer is not responding i.e. all links are unclickable.

**Expected Behaviour**
The footer should be working normally as it does on other pages.

**Steps to reproduce it**
- Go to the support page by selecting it from footer.
- Try clicking any footer links on this page.

**Screenshots of the issue**

support-footer-error

**Would you like to work on the issue?**
Yes!

### PR DESCRIPTION
**Pull request by rajprakash00**
Fixes #3561 

Changes: Fixed the footer on support page which had extra padding due to which route to other links weren't working.

Demo Link: https://fossasia-footer.netlify.app/

### CODE REVIEW

**Comment by rajprakash00** [comment]
@anishagg17 , @akshatnitd  can you review the changes & suggest any more changes required.

**Comment by rajprakash00** [comment]
My bad @elit-altum ,I had some errors showing up in yarn install(turns out due to incorrect installation of yarn package manager) thus I turned to npm.
Is it OK ,now?

**Comment by elit-altum** [comment]
@rajprakash00 2 of your previous commits still have that file. Please squash these commits into 1 & remove the file from that. And it seems you have also updated 2 dependencies. Any reason for that ?

**Comment by rajprakash00** [comment]
@elit-altum after npm install it was showing to fix versions of some package,so I did it(later I came to know it updated the lodash & surge packages & due to which it failed in travis CI)

**Comment by rajprakash00** [comment]
I messed up big time in squashing :frowning_face: due to which my git history is messed up, so I'm gonna close this PR.

**Pull request closed without merging**
