### PR TITLE
Admin Dashboard: Device Tab - Add Device Added Date, Location Map and Edit Device

### LINKED ISSUE #2708: Admin Dashboard: Device Tab - Add Device Added Date and Last Active, show device location, edit device
In the Admin dashboard device tab, please add the following in the table:
* Column "Date Added"
* Column "Last Active"
* Make "Location" clickable and show pop-up map with device location
* In actions tab add icon "Edit Device" that directs to user's device page, which can be accessed by the admin

Screenshot from 2019-07-29 09-05-52

### LINKED ISSUE #2714: My Devices: Add "Date Added", "Last Connected" date and "IP Address"
In the My Devices table (https://susi.ai/mydevices) and actual device page (https://susi.ai/mydevices/[MAC Address] please change the following:
* Change column order as follows: Name | Room | Location | MAC Address | Date Added | Last Connected | IP Address
* Include columns date added, last connected, IP Address (Dates should include time, IP Address shows last used IP address)
* Make each column sortable

Screenshot from 2019-07-29 10-25-20

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2708, Fixes #2714 

Changes: Added device date, location map on hover and edit device.

Demo Link: https://pr-2805-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-08-09 at 7 49 05 PM

### CODE REVIEW

**Comment by mariobehling** [comment]
Please delete screenshots with private data and dont post screenshots with keys or anything. Please use Gimp to delete areas with private data.

**Comment by harsh-jindal** [comment]
@mariobehling 
1. As this also a part of the issue https://github.com/fossasia/susi.ai/issues/2714. I have already asked the mentors how to show the last active and IP address here: https://github.com/fossasia/susi.ai/issues/2714#issuecomment-518005709
2. Clicking on the locations opes a pop up with map(map does not load because of mapkey not available for surge deployment):
Screenshot 2019-08-09 at 1 25 50 PM
3. Edit Device currently opens up a modal to edit device name and room name. I can direct to the user specific device page but there also you have exact same information with same edit access of device Name and room Name. So shall add another tab view which redirects to device specific page ?

4. About the bottom scroll, it is a feature of material ui table which we used across the admin panel. If we need to get rid of that then we need to use some other library. @akshatnitd @fragm3

**Comment by harsh-jindal** [comment]
@mariobehling Made the changes.Please review
Now we have three action tabs:
1. `View`: Which takes you to users my devices page.
2. `Edit`: Opens up a dialog box to edit device name and room.
3. `Delete`: Directly delete the user device.

Edit and Delete can also be performed on my devices page of user by admin.

Last Active Column(Not Added) - need more input for that asked here on gitter : https://gitter.im/fossasia/susi_webclient?at=5d4d81a61dadc42a113e5ead

For bottom scroll, as it is present across the admin, more discussion is needed on what approach should be there.

**Comment by harsh-jindal** [comment]
@mariobehling @akshatnitd @fragm3 Please review. For last Active and last Login IP made a PR on server https://github.com/fossasia/susi_server/pull/1372

**Comment by harsh-jindal** [comment]
@mariobehling Made the changes. Fixed:
1. Restricted device name to 20 characters.
2. Fixed date sorting.

Things not fixed:
1. `Show 100 rows by default and only provide 200, 500 and all as other options` - This again a limitation of the library we are using. It can be done in a way without the library support but as we are planning to move to another library this point will be taken care of there. Also we will need this on other admin tabs also.
2. `Find and implement another library that offers table with multiple lines as the width is breaking the design and not displayed on the same page.` Opened a issue https://github.com/fossasia/susi.ai/issues/2830 for it.

**Pull request merged**
