### PR TITLE
remove white space and mobile view

### LINKED ISSUE #2342: Remove white space and fix mobile view
**Actual Behaviour**

There is an extra white space. Also not have a proper mobile view.

**Expected Behaviour**

Remove white space and fix mobile view in the accounts tab and password tab

**Screenshots of the issue**

Capture
Capture
Capture

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2342  

Changes: Removed white space and fixed mobile view in accounts and password tab

Demo Link: https://pr-2346-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
account
password

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@samagragupta Also fix the pop up menu when we click on edit icon in mobile view.
Screenshot 2019-06-22 at 1 00 57 PM

**Comment by samagragupta** [comment]
@fragm3 
white

**Comment by samagragupta** [comment]
@harsh-jindal Sorry, but I could not understand what's wrong with that?

**Comment by harsh-jindal** [comment]
@samagragupta I don't have this issue. The above GIF is made from your localhost or from susi.ai . Also which browser.
Also I meant when I click on the scroll icon the page scrolls up and then the pop-up menu is shown. Can it be shown the same way as web view.

**Comment by samagragupta** [comment]
@harsh-jindal Its from susi.ai and I am using chrome browser.
Capture

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Can you confirm you have the same issue?

**Comment by samagragupta** [comment]
> @samagragupta Also fix the pop up menu when we click on edit icon in mobile view.
> Screenshot 2019-06-22 at 1 00 57 PM

https://github.com/fossasia/susi.ai/pull/2337#issuecomment-504721145

**Comment by fragm3** [comment]
@harsh-jindal @samagragupta Unable to produce the issue.

**Comment by samagragupta** [comment]
I am using Google Chrome Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by harsh-jindal** [comment]
@samagragupta This issue has occurred in the latest chrome version.
Fix this: (No space)
Screenshot 2019-06-23 at 5 10 02 PM

**Comment by samagragupta** [comment]
@harsh-jindal Done
aa

**Comment by samagragupta** [comment]
@akshatnitd Fixed the Travis

**Pull request merged**
