### PR TITLE
Admin Dashboard: Erroneous dates in analytics #2829

### LINKED ISSUE #2829: Admin Dashboard: Erroneous dates in analytics
The dates in the analytics sections are erroneous. Please see below.

Screenshot from 2019-08-12 14-05-06

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2829

Changes: Fix user, skill statistics in the admin panel

Demo Link: https://pr-2843-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 

Screenshot 2019-08-15 at 11 32 21 PM

### CODE REVIEW

**Comment by fragm3** [comment]
`Devices Added over Time` chart has a problem from the server side and need to be fixed on the server, so we can go ahead with this PR.

**Comment by fragm3** [comment]
@akshatnitd made the change

**Comment by fragm3** [comment]
@harsh-jindal problem from backend, getting:
```
    "deviceAddedOverTime": [
      {
        "timeStamp": "2019-08",
        "count": 2
      },
      {
        "timeStamp": "2019-08-14T19:12:00.949Z",
        "count": 1
      }
    ]
```

**Comment by harsh-jindal** [comment]
@fragm3 Cool, I'll look into it.

**Pull request merged**
