### PR TITLE
fix table overflow for bot builder configuration UI View

### LINKED ISSUE #2894: Fix overflow issue in table in Add your website in Bot Builder
**Actual Behaviour**
Currently the table overflows the dimension.

**Expected Behaviour**
Fix it.

**Screenshots of the issue**
Screenshot 2019-08-29 at 8 50 38 AM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by Tanish0019**
Fixes #2894 

Changes: Wrapped the table inside a div with overflow-x set to auto

Demo Link: https://pr-2908-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
Screen Shot 2019-09-11 at 3 18 56 PM

### CODE REVIEW

**Comment by Tanish0019** [comment]
Okay, I'll fix that!

**Comment by Tanish0019** [comment]
@akshatnitd please take a look. I added a delete icon instead of plain text if that's okay.
Screen Shot 2019-09-18 at 12 58 09 AM

**Comment by Tanish0019** [comment]
@akshatnitd done!

**Comment by plxity** [comment]
@Tanish0019 Create a new branch whenever you work on some issue. :)

**Comment by Tanish0019** [comment]
@plxity Noted! Just looked at a proper git workflow tutorial. Will do that in my next PR. Is there anything that needs to be changed in this one?

**Comment by plxity** [comment]
@Tanish0019 No, I think it's fine. As it has been approved by @akshatnitd sir.

**Pull request merged**
