### PR TITLE
remove outline from share buttons

### PR DESCRIPTION
**Pull request by makoteq**
fix to https://github.com/fossasia/susi.ai/issues/3019
### Then 
68233942-3e2b3e00-0026-11ea-8082-5c9bf608c224

### CODE REVIEW

**Comment by makoteq** [comment]
Updated! @dipu989

**Comment by dipu989** [comment]
Looks good to me! Well done. Let's wait for other mentors to review.

**Comment by makoteq** [comment]
> Looks good to me! Well done. Let's wait for other mentors to review.

@dipu989  can you tag other mentors to review my PR

**Comment by dipu989** [comment]
@akshatnitd Can you please review this PR and get this merged! Thanks.

**Pull request merged**
