### PR TITLE
Removed horizontal scrollbars on Edge and Firefox

### LINKED ISSUE #3506: Removing horizontal scroll-bars from the browse skills container
**Actual Behaviour**

**For Mozilla Firefox and Microsoft Edge**

Currently, the browse skills div has both, the scroll-bars and the scroll buttons which are redundant in functionality.
The scroll bars are also present on the div having only one skill which is not required.

Removing the scroll bars and only using the scroll-buttons will
- Help to remove functionality redundancy
- Remove the extra webpage space being taken up by scroll-bars
- Will create a more appealing UI

ScreenShots:
*For a single skill*

Single-Scroll-Bar

*Scroll bar and button redundancy*

File-Scroll-Bar-Issue

<---------------------------------------->

**Expected Behaviour**

*For a single skill (fixed)*

Single-Scroll-Bar-Solved

*Scroll bar and button redundancy (fixed)*

File-Scroll-Bar-Solved

**Steps to reproduce it**
- Go to the main page
- Navigate/browse the skills presented on the page

**Would you like to work on the issue?**
Yes. I am working on it.

### PR DESCRIPTION
**Pull request by elit-altum**
Fixes #3506 

Changes:
The current codebase only hid the horizontal scrollbars on the Browse Skills container in Chrome only. This PR enables that feature across Edge and Firefox as well. 

Demo Link: https://pr-3509-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 

__Mozilla Firefox__
File-Scroll-Bar-Solved-Firefox

__Microsoft Edge__
File-Scroll-Bar-Solved-Edge

### CODE REVIEW

**Comment by snitin315** [comment]
I think your local git settings are incorrect please check. (user email should be same as the email you are using on github)

**Comment by elit-altum** [comment]
> 
> 
> Also, change for unnecessary scrollbar in the settings page and wherever needed?
@mohitm15 
Sure I can do that. Please provide the routes/pages where you think this can be implemented.

**Comment by mohitm15** [comment]
> > Also, change for unnecessary scrollbar in the settings page and wherever needed?
> 
> @mohitm15
> Sure I can do that. Please provide the routes/pages where you think this can be implemented.

Refer #3437 @elit-altum

**Comment by elit-altum** [comment]
> 
> 
> > > Also, change for unnecessary scrollbar in the settings page and wherever needed?
> > 
> > 
> > @mohitm15
> > Sure I can do that. Please provide the routes/pages where you think this can be implemented.
> 
> Refer #3437 @elit-altum

Thank you @mohitm15 . Fixed this as well.

**Comment by elit-altum** [comment]
@snitin315 I have made the required changes and squashed the commits. Please review.

PS: Thank you for pointing out the local git settings difference.

**Comment by mohitm15** [comment]
@elit-altum have you checked everywhere, I just give instance of such scrolling behaviour in settings page. ?

**Comment by elit-altum** [comment]
> @elit-altum have you checked everywhere, I just give instance of such scrolling behaviour in settings page. ?

Yes @mohitm15 the other related pages have been working well enough.
@akshatnitd Please review.

**Pull request merged**
