### PR TITLE
Add theme color and loading text

### LINKED ISSUE #3116: Theme color for mobile devices
**Actual Behaviour**
Currently, there's no specific theme for the web app.
**Expected Behaviour**
There should be a theme color that matches the theme of SUSI.AI web app.
**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by MuhammadWasif**
Fix #3116 
Currently, there's no theme color for mobile devices. I've added a theme color that changes theme of browser according to SUSI.AI theme. (You can see theme changed on gif below).
Also, the web pages shows text *loading...* until the main contents load.
**Screenshot of changes:**
ezgif-7-3d02d3d908ef
**Demo Link**:
https://sad-visvesvaraya-f4a745.netlify.com/

> Please test on mobile device for better experience

### CODE REVIEW

**Comment by mariobehling** [comment]
Please open an issue and match this PR with an issue. While we could understand what you are doing here, it is important to follow best practices from the beginning. Otherwise it will be increasingly difficult to stick to good development practices and developer exchange. Thanks! 

Our best practices are here for your reference: https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/

**Comment by MuhammadWasif** [comment]
@mariobehling I've done the changes. Sorry for mistake. I've opened an issue and associated this with that issue. Please check now.

**Comment by MuhammadWasif** [comment]
These days, almost every website has a theme that enhance the UI in mobile devices. Theme can make SUSU.AI web app feels like a mobile app.

**Comment by MuhammadWasif** [comment]
> How is adding meta tag for theme useful here?

These days, almost every website has a theme that enhance the UI in mobile devices. Theme can make SUSU.AI web app feels like a mobile app.

**Comment by mariobehling** [comment]
Sorry, this is of low priority and too small of an improvement to be relevant for the project. Closing it therefore. Thanks.

**Pull request closed without merging**
