### PR TITLE
CSS Fixes in skill description

### LINKED ISSUE #2280: Css fixes in skills description
**Actual Behaviour**

Css bugs in skills description.

**Expected Behaviour**

- Fix mobile view in skills description.
- Remove scrolling
- Change SVG of edit icon

**Screenshots of the issue**

Capture

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2280 

Changes: 
- Fixed mobile view in skills description.
- Removed scrolling
- Changed SVG of the edit icon

Demo Link: https://pr-2287-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Capture

### CODE REVIEW

**Comment by samagragupta** [comment]
@akshatnitd Sorry for the inconvenience. Made the changes

**Comment by samagragupta** [comment]
@fragm3 Which unwanted changes? 🤔

**Comment by fragm3** [comment]
@samagragupta Care to see Files Changed tab? Let's first teach elementary stuff to you.

**Comment by fragm3** [comment]
Unwanted changes:

Screenshot 2019-06-18 at 12 01 19 AM

Screenshot 2019-06-18 at 12 01 25 AM

**Comment by samagragupta** [comment]
@fragm3 This all happened because another PR was merged which has deleted this file.

**Comment by samagragupta** [comment]
@fragm3 Deleted the files

**Comment by samagragupta** [comment]
@fragm3 Its working fine in localhost.
Maybe surge link is not working due to Travis build

fe
fe1
fe2

**Comment by samagragupta** [comment]
@fragm3 @akshatnitd Should I follow these steps.
Capture

**Comment by samagragupta** [comment]
@fragm3 Please review.
The surge link is working fine.

**Comment by harsh-jindal** [comment]
@samagragupta I don't know how does this fix look good to you. Haven't you seen the rating is coming out of the container ?? 
Also remove the padding in mobile view. So that the container has more width.

**Comment by akshatnitd** [comment]
It should look like this after the change. Please make changes accordingly. - 
Screenshot 2019-06-20 at 10 49 23 AM

**Comment by samagragupta** [comment]
fe50

**Comment by samagragupta** [comment]
@mariobehling @akshatnitd Made the change
Capture

**Comment by harsh-jindal** [comment]
@samagragupta Couple of bugs are still present in different mobile views. I guess they can be picked by later by someone else.

**Pull request merged**
