### PR TITLE
Add speech box for skill example sentences on front, cat and all pages with skills

### LINKED ISSUE #2511: Add speech box for skill example sentences on front, cat and all pages with skills
Add a speech box for skill example sentences to the front page skills, category pages and all pages that show skills same as the skill detail page and link this speech box to provide answers in the chat box.

Screenshot from 2019-07-11 12-20-52

Screenshot from 2019-07-11 12-20-15

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2511 

Changes: Now if you click on skill example it appears on the chat.
Demo Link: https://pr-2538-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-07-13 at 9 57 31 PM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
testSkillExampleKey:  is used so that if the user clicks again on the test example after clicking on it once, the message section state change will give the answer again.

testSkillExampleQuery: is used so that on toggle or on full screen the answer is not generated again.

**Comment by harsh-jindal** [comment]
Reload the page while checking in mobile view.

**Comment by mariobehling** [comment]
There was one good thing about the previous way: We could query the answer just by using a URL, e.g. https://susi.ai/chat?testExample=Quote%20by%20Donald%20Trump

How can we still have this feature?

**Comment by harsh-jindal** [comment]
@mariobehling I am implementing this in such a way if u query `?testExample=[question]` on any page(any URL) the answer shall come up on the chat window.

**Comment by mariobehling** [comment]
Please also add this feature to the front page. So, every skill should have the speech box on the front page as well.

**Comment by harsh-jindal** [comment]
Sure will add that in this PR.

**Comment by harsh-jindal** [comment]
@akshatnitd The problem in this implementation is that if the user clicks twice on the text example, the second time it will not get executed. Also if the senario is : first the user clicks on test example, then writes something in the chat and again clicks on the example the answer will not be generated as the testSkillExampleQuery has not changed.

**Comment by harsh-jindal** [comment]
@mariobehling @akshatnitd @fragm3 Please review.
Can you also tell where to place the test example skill bubble on the main page for each card?

**Comment by mariobehling** [comment]
> @mariobehling @akshatnitd @fragm3 Please review.
> Can you also tell where to place the test example skill bubble on the main page for each card?

There is already the example text on the card on the front page. Add the text in the bubble and make it clickable. Keep the rest of the card itself to be clickable and direct it to the skill page. Only the bubble should have the link to open the example in the chat box.

Screenshot from 2019-07-16 05-08-51

**Comment by harsh-jindal** [comment]
@fragm3 I have explained the need To use the `testSkillExampleKey`. If we can't use Math.random(),can we set `testSkillExampleKey` as 0 and increase it by one when the test example is clicked ?

**Comment by harsh-jindal** [comment]
@fragm3 Remove the `math.random()` function. Please review

**Comment by mariobehling** [comment]
Screenshot from 2019-07-16 09-56-20

Compare to:
Screenshot from 2019-07-16 09-58-43

Please:
* implement/reuse the same box style as on skill pages
* Slightly increase the space to the left icon

**Comment by harsh-jindal** [comment]
@mariobehling @akshatnitd Made the changes. Please review

**Comment by mariobehling** [comment]
@harsh-jindal Thanks!
@akshatnitd Let's follow up on remaining points in upcoming issues. I am merging this.

**Pull request merged**
