### PR TITLE
Fix bugs in skill creator and bot builder

### LINKED ISSUE #2761: Bot Wizard: Move Bottom Buttons, Save etc. closer to upper box and leave enough space below
The save/draft buttons on the bottom of the wizard are not close enough to the upper box and don't have spacing below. They are difficult to reach. 

Please improve on this.

Screenshot from 2019-08-01 08-13-42

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2761 #2760 

Changes: Made the changes as specified in the issue.

Demo Link: https://pr-2762-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-08-01 at 1 04 13 PM
<------>
Screenshot 2019-08-01 at 1 04 29 PM
<---------->
Screenshot 2019-08-01 at 1 07 31 PM

### CODE REVIEW

**Comment by mariobehling** [comment]
Please also take care of the buttons. 
1. "Create" on the bottom is shorter than cancel even though it has the same number of charaters. Spacing does not seem same.
2. Swtich position of "Create" and "Cancel" button on skill creator.

**Comment by harsh-jindal** [comment]
@mariobehling Fixed.

**Comment by harsh-jindal** [comment]
@samagragupta where exactly ?

**Comment by samagragupta** [comment]
At the top of the preview.

**Comment by harsh-jindal** [comment]
@akshatnitd @fragm3 Made the changes.
@samagragupta I don't get where are you asking to add padding. If you are saying to the heading Preview, then it cannot be done as it has to be in the same line as `create a susi skill`

**Comment by harsh-jindal** [comment]
@akshatnitd Done.
Screenshot 2019-08-02 at 7 23 33 AM

**Comment by harsh-jindal** [comment]
@samagragupta When you the scroll the page, the component will go up. Idk why you want padding there, it will out of place with skill creator component on the left.

**Comment by samagragupta** [comment]
@harsh-jindal It should be fixed when scrolled.

**Comment by harsh-jindal** [comment]
@akshatnitd Made the changes. 
Shall I make the changes suggested by samagara?
Screenshot 2019-08-02 at 3 16 33 PM
Screenshot 2019-08-02 at 3 16 45 PM

**Pull request merged**
