### PR TITLE
Search Enhance #2532, #2531, #2536

### LINKED ISSUE #2532: Redirect to Browse skills search on search enter
**Actual Behaviour**

With PR https://github.com/fossasia/susi.ai/pull/2527, we can enhance it further

**Expected Behaviour**

We can enhance it further for other pages, by redirecting to skills page results on the keyboard enter key

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2532, #2531, #2536

Changes: 
- [x] Redirect to homepage in search enter
- [x] Change the style of the language dropdown and make it smaller
- [x] Change style of select of search type, make it similar to Amazon
- [x] Implement frontpage for mobile

Demo Link: https://pr-2537-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
Screenshot 2019-07-13 at 9 18 39 PM
Screenshot 2019-07-13 at 9 19 02 PM

Mobile view
Screenshot 2019-07-13 at 10 16 05 PM
Screenshot 2019-07-13 at 10 16 36 PM

### CODE REVIEW

**Comment by mariobehling** [comment]
Please delete "Skills" and the burger menu on the left.

**Comment by mariobehling** [comment]
Any way to make language dropdown smaller, maybe decrease padding to left and width a bit?

**Comment by mariobehling** [comment]
Screenshot from 2019-07-13 19-52-23

Please move the X a bit to the right. Ensure there is a space.

**Comment by mariobehling** [comment]
Always show search bar in desktop view. Don't show X.
Screenshot from 2019-07-13 20-10-27

**Comment by fragm3** [comment]
@mariobehling made the changes

**Comment by mariobehling** [comment]
* Please keep styles consistent: Padding/Spacing in buttons should be same - see down arrow on both buttons "All" and "languages"
* At the same time actually do leave some spacing. Don't make it too close, e.g. the arrow spacing
* Also leave some space next to the logo

Screenshot from 2019-07-13 22-14-16

**Comment by mariobehling** [comment]
I'm not able to get out of search on mobile view anymore.
Screenshot_2019-07-13-22-22-53-330_com android chrome

**Comment by fragm3** [comment]
@mariobehling made the changes: 

Screenshot 2019-07-14 at 3 31 56 AM

**Comment by mariobehling** [comment]
Thanks!

**Comment by mariobehling** [comment]
@akshatnitd Merging this. If any more changes are required let's do it in the next milestone.

**Pull request merged**
