### PR TITLE
Now the menu that pops on hovering on "?" is completely inside the display console

### LINKED ISSUE #2671: menu under "?" is not completely inside the screen
**Actual Behaviour**
menu that pops by hovering on "?" is not completely inside the screen 
susi1
**Expected Behaviour**
menu should be completely inside the the screen

**Would you like to work on the issue?**
Yes , i would like to work on it

### PR DESCRIPTION
**Pull request by tanujvyas10**
Fixes #2671

**Changes: Now the menu that pops on hovering on "?" is completely inside the display console**
**Demo link**:
[https://humdrum-lace.surge.sh/](https://humdrum-lace.surge.sh/)

**SCREENSHOT AFTER THE BUG REMOVING**

final

### CODE REVIEW

**Comment by tanujvyas10** [comment]
@fragm3  and @samagragupta  hello sir, i have made changes to fix the issue .Please review my work.Thank you

**Comment by tanujvyas10** [comment]
> @tanujvyas10 IMO, this is not the right way to solve this issue, Because for screens smaller than 1200px this will still happen. The search bar width shall be flexible to the space available along with a max-width for larger screens.

sir, right now the susi.ai website is not responsive.I have made the changes such that ,if in future ,the web dev. team works on the responsiveness of the website ,it will get accommodate with those changes and also alteration will take place at that time when the team will start work on the responsiveness of the website.I made the changes according to the current requirement of the website.

**Comment by tanujvyas10** [comment]
> @tanujvyas10 IMO, this is not the right way to solve this issue, Because for screens smaller than 1200px this will still happen. The search bar width shall be flexible to the space available along with a max-width for larger screens.

sir ,right now the website is not responsive , but i made changes according to current specification of the website. If you are asking for responsive header , i think whole website need to get responsive feature, not just header alone. I have made alteration in the header according to current situation and requirement of the website.

**Comment by harsh-jindal** [comment]
@tanujvyas10 We need to go on the responsiveness component by component, you cannot make the whole website responsive in one PR. Please create issues and work on then where you feel there is responsiveness issue component by component. For now make the header responsive in this PR.

**Pull request closed without merging**
