### PR TITLE
added mui based theme to change theme of component

### LINKED ISSUE #2082: Use MaterialMUITheme for theming
**Actual Behaviour**

Not present

**Expected Behaviour**

Use MaterialMUITheme for theming consistency across the chat application, will help in achieving light and dark mode.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by kpulkit29**
Fixes #2082 

Changes: Added Theme Provider (Material UI) to control the theme of the component. Based on the user settings theme provider would manage the color scheme itself.

Demo Link: https://pr-3032-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
Screenshot 2019-11-09 at 7 35 42 PM
Screenshot 2019-11-09 at 7 35 51 PM
Screenshot 2019-11-09 at 7 35 58 PM
Screenshot 2019-11-09 at 7 36 03 PM

### CODE REVIEW

**Comment by AuraOfDivinity** [comment]
@kpulkit29  isn't this ultimately the same thing done in https://github.com/fossasia/susi.ai/pull/2973 ?

**Comment by kpulkit29** [comment]
Yes I guess but this one uses the more conventional way of doing it as defined in Material UI docs

**Comment by kpulkit29** [comment]
Theming is now managed throughout the app

**Comment by AuraOfDivinity** [comment]
IMHO the only difference is declaring the the colors on the MUI palette which I didn't have in mind while making the initial #2973 PR (which happened to be more focused on getting some feedback from the maintainers so that I could make the required changes). 

@akshatnitd  @kpulkit29 any thoughts on what I should do with my original PR?

**Comment by kpulkit29** [comment]
Well, @AuraOfDivinity there is a comment on your PR regarding some broken functionality. I guess that might be an issue. Other than that I don't see any thing wrong.

**Comment by AuraOfDivinity** [comment]
I will make the changes requested and make another PR later today!

**Comment by kpulkit29** [comment]
@akshatnitd I have made the changes discussed. Kindly refer to #2981

**Comment by kpulkit29** [comment]
@akshatnitd  do I need to define these constants by myself, don't see any such thing defined for light and dark mode separately

**Comment by kpulkit29** [comment]
@akshatnitd Please suggest on how can I go ahead with the changes  you mentioned. Currently the  for light and dark theme redux only gives back the theme name and not primary, secondary colors etc.

**Comment by AuraOfDivinity** [comment]
@akshatnitd Could you also kindly give some feedback on https://github.com/fossasia/susi.ai/pull/2973 on **whether or not I should completely scrap** the PR? 

The deployment can be seen here - https://pr-2973-fossasia-susi-web-chat.surge.sh/  

Contrary to @kpulkit29 's PR I've done the theming using the styled-theming package.  A really simple example of styled-theming looks like this,



The way I've themed is a lot similar to the expected behavior you mentioned in one of the previous comments.  As of now almost all of the components in my PR are themed separately. The next step would be the abstract out those separately themed similar components in to a single file so that for example we could theme all the Paper elements of the project from a single file.

Thanks in advance!

**Comment by kpulkit29** [comment]
> @kpulkit29 It is still not present. We have a file `colors.js` which have the colors that are being used in the app. Feel free to add object variables `LIGHT_THEME`, `DARK_THEME` in that file and use these constants while using `createMuiTheme`.

okay thanks

**Comment by kpulkit29** [comment]
@akshatnitd  I went through a the material UI docs turns out that only some values can when using MuiTheme. Kindly refer to https://material-ui.com/customization/default-theme/ .Only the values mentioned in pallete can be modified.`export const light = {
  header: '#4285f4',
  pane: '#fcfcfc',
  body: '#f5f5f5',
  composer: '#f9f9f9',
  textarea: '#fff',
  button: '#4285f4',
};
`
Not all the values given in colors.js can be used by MuiTheme. However some values like text, background etc can be modified. I would like to go ahead with this idea.

**Comment by kpulkit29** [comment]
> @akshatnitd I went through the material UI docs, turns out that only some values can modified when using MuiTheme. Kindly refer to https://material-ui.com/customization/default-theme/ .Only the values mentioned in pallete can be modified.`export const light = { header: '#4285f4', pane: '#fcfcfc', body: '#f5f5f5', composer: '#f9f9f9', textarea: '#fff', button: '#4285f4', }; export const dark = { header: '#4285f4', pane: '#071e3d', body: '#0F2645', composer: '#1E3554', textarea: '#071e3d', button: '#4285f4', }; `
> Not all the values given in colors.js can be used by MuiTheme. However some values like text, background etc can be modified. I would like to go ahead with this idea. Should I proceed with this?

@akshatnitd Would need your suggestion to go ahead with this.

**Comment by kpulkit29** [comment]
@akshatnitd Please let me know if I can go ahead with the approach I am thinking.

**Comment by paras151** [comment]
> @kpulkit29 It is still not present. We have a file `colors.js` which have the colors that are being used in the app. Feel free to add object variables `LIGHT_THEME`, `DARK_THEME` in that file and use these constants while using `createMuiTheme`.

I think that colors present in colors.js are only used for the chat window, whereas for other components for eg. in settings page , the colors of different components have been set manually acc. to light or dark theme, so I think the color for text in input should not be added to colors.js. 
Am I correct?

**Comment by kpulkit29** [comment]
Th point here is header, pane color etc mentioned in colors.js cannot be used along with createMUITheme as it allows overriding only some properties

**Comment by akshatnitd** [comment]
Closing due to inactivity

**Pull request closed without merging**
