### PR TITLE
Add login in the setup page[Smart Speaker] #2824

### LINKED ISSUE #2824: Add login in the setup page[Smart Speaker]
**Actual Behaviour**
The setup page which is used to setup the device currently doesn't have fields to enter login credentials but this is however implemented in the backend and is used to register the device online.

The input names are - 
- `auth` - If credentials are given then the value should be `authenticated` otherwise `anonymous`
- `email` - SUSI.AI registered email
- `password` - password for the given account

The endpoint remains the same - `reboot` just the above fields are to be added with the correct names.

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2824, #2852 

Changes: 
1. Add login in the setup page
2. Remove wake button

Demo Link: https://pr-2847-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 

Screenshot 2019-08-15 at 1 26 45 AM

### CODE REVIEW

**Comment by fragm3** [comment]
@alok760 please review.

**Comment by mariobehling** [comment]
Could you change the following in this PR, please as well:
* Change the SUSI.AI logo to match the logo on the other pages
* Reduce the space between "Email" and "Password" in the SUSI.AI forms fields
* Change as follows:
    * Setup the WiFi for Your Smart Speaker
    * Choose Hotword Recognition
    * Add Smart Speaker to Your SUSI.AI Account
        * below add in smaller font "This will allow you to use private skills you created online and synchronize your data. You cannot do this later. If you don't have an account on SUSI.AI [you can set it up here](https://susi.ai) now.
        * Provide radio buttons here a) Connect to SUSI.AI b) Anonymous Mode (user does not need to enter credentials)
* Instead of existing text above blue button change as follows:
   * Thank you for entering your details. You can now save your data. After you hit the "Save" button the device will shut down and reboot. The smart speaker will connect with your WiFi network and add the device to your SUSI.AI account, if you provided your credentials. If the smart speaker is not able to connect with the WiFi it will restart and open a hotspot again. You can configure the device again.
   * If you would like to reset your device later manually (to get back here) you can press the device button for 10 seconds. The device will reset and you can access it again through the hotspot and configure it.
    * Save and Reboot

**Comment by fragm3** [comment]
@mariobehling made the changes:
Screenshot 2019-08-15 at 9 39 10 PM

**Comment by alok760** [comment]
@fragm3 Add the following vars to the request that you're sending to the `/reboot` endpoint
`room_name` : Add a default value for now
`stt` and `tts`: The default value should be 'google'

**Comment by mariobehling** [comment]
1. Increase space above "Thank you for entering your details..."
2. There is a small mistake in my earlier text for the SUSI.AI account. Please use this updated one: "This will allow you to use private skills you created online and synchronize your data. You cannot do this later. If you don't have an account on SUSI.AI, please connect to the Internet sign and up at SUSI.AI now."
3. Please show the SUSI.AI login options below each other and only show "Email/Password" when the user chooses this option.
Screenshot from 2019-08-16 05-49-56

**Comment by mariobehling** [comment]
Screenshot from 2019-08-16 05-49-56

**Comment by fragm3** [comment]
@mariobehling made the changes:

Screenshot 2019-08-16 at 12 36 47 PM

**Comment by fragm3** [comment]
@alok760 made the changes:
Screenshot 2019-08-16 at 1 04 20 PM

**Pull request merged**
