### PR TITLE
Footer: Increase gray area

### LINKED ISSUE #2613: Footer: Increase gray area bottom by about 30-40 px to show the menu above the chat icon
The contact link is currently hidden by the chat icon on top. Please increase gray area bottom by about 30-40 px to show the menu above the chat icon when scrolling it up.

Screenshot from 2019-07-17 11-08-27

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2613

Changes: Increased the gray area to show the menu above the chat icon when scrolling it up.

Demo Link: https://pr-2615-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
Capture

### CODE REVIEW

**Comment by mariobehling** [comment]
I think a bit more would be good.

**Comment by samagragupta** [comment]
@mariobehling increased the padding.
Capture

**Comment by samagragupta** [comment]
@harsh-jindal You mean top and bottom padding should be same.

**Comment by harsh-jindal** [comment]
@samagragupta yes I meant that. But I think then chat bubble will overlap with contact tab. @mariobehling shall we have the text vertically aligned to center ?

**Comment by mariobehling** [comment]
No need for vertical alignment. Let's test this for a while.

**Comment by samagragupta** [comment]
> @harsh-jindal You mean top and bottom padding should be same.

@mariobehling We can make both padding same. If it looks good. Like this:
Capture

**Pull request merged**
