### PR TITLE
Add Loader in missing places #2299

### LINKED ISSUE #2299: Add Loader in missing places
**Actual Behaviour**

 Loader missing in 

- Settings component
- Admin Component

**Expected Behaviour**

Add it in missing places

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2299

Changes: 

- Add loader System Settings Config Table
- Fix Skill Tab Skills loading used to show `no records to display`
- Removed redundant handlers in skills tab

Demo Link: https://pr-2387-fossasia-susi-web-chat.surge.sh

Screenshots of the change:

Screenshot 2019-06-30 at 12 54 55 AM

### CODE REVIEW

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal 

I have the following questions, please address them:

- Use material table for config keys? Gives a nice loading effect and would be consistent with other tables. 
- Add confirmation of Delete Key, Confirm update, addition?
- Add loading in button in skills tab in admin

**Comment by harsh-jindal** [comment]
@fragm3 We can use material table for config keys if in the future we have many keys and we want to have search options.
Confirmation Delete key dialog is already present for the config key. 
Also confirmation create i think is not required as admin only has the write to create keys.

**Comment by fragm3** [comment]
@harsh-jindal confirmation for delete key is not present

**Comment by fragm3** [comment]
@akshatnitd I can either hide the table to show the Loader on center or we can use this alignment, can't be done inside Table

**Comment by harsh-jindal** [comment]
@fragm3 While deleting key we can have the admin enter key name before deleting as a confirmation. I don't think we need to have two dialog boxes for deletion of config key.

**Comment by fragm3** [comment]
@harsh-jindal I didn't add 2 Dialog

**Comment by harsh-jindal** [comment]
@fragm3 I didn't mean you have added two dialogs. I meant we can have the admin enter the key name before deletion as a confirmation. Can you please tell your idea? Maybe I'm missing your meaning of `confirmation of Delete Key`

**Comment by fragm3** [comment]
@harsh-jindal I thought, as we have less number of keys, we don't need confirmations. Should I add confirmation @akshatnitd like harsh is saying? or let it be?

**Comment by fragm3** [comment]
Updated:
Screenshot 2019-06-30 at 12 37 42 PM

**Comment by akshatnitd** [comment]
@harsh-jindal @fragm3 Confirmation is good idea. Can be handled in a separate PR. 
We should ideally make the confirmation dialog a shared component. It is being used with same design at multiple places.

**Pull request merged**
