### PR TITLE
SUSI Smart Speaker Device Control page independent of login #2784

### LINKED ISSUE #2784: Make SUSI Smart Speaker Device Control page independent of login
Currently, to control the device, the user must log in and go to their added devices. This creates the following problems - 
- what if the user doesn't want to login.
- After login, some device must be added to the account to access the control page.
- Online accounts are not synchronised and the user must create a new account.
TO DO - 
- Make the control page independent of login and only available on the local build

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2784

Changes: Make SUSI Smart Speaker Device Control page independent of login

Demo Link: https://pr-2820-fossasia-susi-web-chat.surge.sh

Screenshots of the change:

Screenshot 2019-08-11 at 3 10 22 PM

Screenshot 2019-08-11 at 3 10 29 PM

Screenshot 2019-08-11 at 3 01 47 PM

### CODE REVIEW

**Comment by fragm3** [comment]
@alok760 please review

**Comment by fragm3** [comment]
@akshatnitd made the changes

**Comment by mariobehling** [comment]
I see you never add a space in front of "(". I cannot possibly open an issue for these small things everywhere. Could you please provide a fix for this.

**Comment by fragm3** [comment]
@mariobehling will incorporate this in some other pr

**Pull request merged**
