### PR TITLE
SkillCreator, Botbuilder general improvements

### LINKED ISSUE #2738: Make Create Pages and Add Device Page more Consistent
The design of the create and add device page is inconsistent. The first row of the page has a different spacing. Device page has a gray background area. Below is a screenshot for the bot page. Please:
* design bot and create skill page according to this layout
* implement a gray background as shown in the picture (following the device page).
* For a new skill or bot always show the category "General" as pre-selected
* For a new skill or bot always show the language "English" as pre-selected
* Design the skill or bot name field in the same way as category and language field
* Make the field locations responsive (on large screen they should show up next to each other and move to the next line when there is not enough space, e.g. when the preview area is shown)
* Show the SUSI.AI logo in the picture field with a + sign on the bottom right corner (or sth. similar / If the user does not have their own picture, it can simply show the SUSI.AI logo)

Screenshot from 2019-07-30 15-32-10

The screenshot shows the full page view without the preview box. Keep the preview box area with the white background as is.

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2738, #2644, #2694, #2755

Changes: 
- [x] Remove image required for skillCreation, botBuilder
- [x] Fix language options on category change
- [x] UI bugs of skill menu
- [x] Responsive in large views
- [x] Remove chat icon from botbuilder, skillCreator, Admin panel

Demo Link: https://pr-2740-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
Screenshot 2019-07-30 at 11 18 30 PM
Screenshot 2019-07-30 at 11 19 08 PM

### CODE REVIEW

**Comment by mariobehling** [comment]
This PR does not solve all the points of https://github.com/fossasia/susi.ai/issues/2738 yet and does not implement the common design in the bot and skills creator.

Screenshot from 2019-07-30 15-32-10

But: You could also resolve the remaining points in a follow up PR, if it is too much.

**Comment by fragm3** [comment]
Will make skillbuilder, botbuilder related changes here

**Comment by mariobehling** [comment]
Please also make spacing of skills page consistent compared to "device" page.

compare:
Screenshot from 2019-07-31 01-41-41

and
Screenshot from 2019-07-31 01-42-02

**Comment by mariobehling** [comment]
Could you also take out the general SUSI.AI chat launcher, please? Just keep the launcher for the preview of the skill.

Screenshot from 2019-07-31 02-04-46

**Comment by mariobehling** [comment]
Furthermore please make the top line and > and < icons in one line with the left side skill editor, please.

Screenshot from 2019-07-31 02-08-45

Screenshot from 2019-07-31 02-09-03

**Comment by mariobehling** [comment]
1. Good the changes on the skills creator. Please also make the same changes on the bots creator page.
2. On full page view also ensure the right hand side is same as device page. (the < icon can overlap if necessary)
3. The scroll over of the code icons on the top right etc. should stay round shape. See screenshot below.

Screenshot from 2019-07-31 17-07-55

**Comment by fragm3** [comment]
@mariobehling made the changes

**Comment by mariobehling** [comment]
Nice!

The right-hand side still has a bigger margin than the margin to the scroll bar on the device page.

Screenshot from 2019-07-31 20-09-08
Screenshot from 2019-07-31 20-08-33
Screenshot from 2019-07-31 20-07-48

**Comment by mariobehling** [comment]
Position "Preview" in the same area on skill and bot creator page. 
* Keep a small margin above the word, please.
* Center the word

Screenshot from 2019-07-31 20-15-28

**Comment by fragm3** [comment]
@mariobehling @akshatnitd made the changes

**Comment by mariobehling** [comment]
> See spacing between areas as well:
> Screenshot from 2019-07-31 03-01-05

Please follow the same spacing size as on the device page.

**Comment by fragm3** [comment]
@mariobehling made the changes.

**Pull request merged**
