### PR TITLE
Enhance multi search functionality #2473 part 2

### LINKED ISSUE #2473: Enhance search functionality
Please change the text in the search bar to "Search for Skills" instead of "Search".

Screenshot from 2019-07-06 19-15-30

Add filters as a drop down menu on the side within the search box with ticks:
* Search in
  * [ ] Names
  * [ ] Description
  * [ ] Examples
  * [ ] Code
  * [ ] Developers

Any other filter options that come to your mind?

Follow material UI but take inspiration from Amazon dropdown menu.

Screenshot from 2019-07-06 19-20-11

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2473

Changes: Add multi select search

Demo Link: https://pr-2527-fossasia-susi-web-chat.surge.sh

Screenshots of the change:

Screenshot 2019-07-13 at 12 01 56 AM

Screenshot 2019-07-13 at 12 02 01 AM

Screenshot 2019-07-13 at 12 02 10 AM

### CODE REVIEW

**Comment by mariobehling** [comment]
Would it be possible to solve this issue about moving the search bar to the top into the menu as well? https://github.com/fossasia/susi.ai/issues/2509

**Comment by fragm3** [comment]
@mariobehling sure, on it

**Comment by fragm3** [comment]
Screenshot 2019-07-13 at 1 15 19 AM

Screenshot 2019-07-13 at 1 15 35 AM

@mariobehling made the changes.

**Comment by fragm3** [comment]
@akshatnitd when no search filters are selected, what should be done?

**Comment by fragm3** [comment]
@mariobehling how about we move it to left column Above `New Arrivals`

**Comment by mariobehling** [comment]
@fragm3 These two search boxes are connected and they need to be positioned together. We can improve the look of the language box, e.g. make it like Amazon, but we go step by step.

**Comment by fragm3** [comment]
@mariobehling okay, then let's consider mobile view in next pr as well, would be tough with less space @akshatnitd

**Comment by mariobehling** [comment]
Sure. Please take out the "Skills" menu item. Skills is the start page now and we will have a "Create" menu item on the right of the user name then.

**Comment by akshatnitd** [comment]
Okay @fragm3

**Comment by fragm3** [comment]
@akshatnitd @mariobehling made the changes.

Screenshot 2019-07-13 at 3 19 26 AM

**Comment by akshatnitd** [comment]
Skills is still present. Please remove it. Also, it would be better if we have a max-width to the languages dropdown. It can be handled in mobile view PR.

**Comment by harsh-jindal** [comment]
@fragm3 Fix the positioning of "sort by" and the icons.
Screenshot 2019-07-13 at 8 58 07 AM

**Comment by mariobehling** [comment]
We are always searching for skills not matter what filter we are using. People might not be aware of it as on other sites you can search for products, web etc. Therefore please show in the text field "Search Skills" no matter what filter is used.

Also please set the standard filter to "All".

Screenshot from 2019-07-13 10-45-22

**Comment by fragm3** [comment]
@mariobehling @akshatnitd @harsh-jindal made the changes

Screenshot 2019-07-13 at 3 19 26 AM

**Comment by mariobehling** [comment]
Ok, thanks.

**Pull request merged**
