### PR TITLE
Fix chat icon in topbar and scroll to bottom

### LINKED ISSUE #2718: Chat box: Opening it does not go to end of conversation and Top icon does not close chat box
Screenshot from 2019-07-29 11-46-19

Please fix the following:
1. Opening the chat box does not go to end of conversation. 
2. Top icon does not close chat box when the chat box is open.

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2718 

Changes: 
Fix chat icon in topbar
scroll to the bottom when chat is open

Demo Link: https://pr-2724-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@samagragupta I don't understand why have you copy pasted @fragm3 code from the PR https://github.com/fossasia/susi.ai/pull/2723 here

**Comment by fragm3** [comment]
This is not acceptable, @akshatnitd @mariobehling

**Comment by samagragupta** [comment]
Sorry

**Comment by akshatnitd** [comment]
@samagragupta It is not all acceptable to see that you copied code from other PR. Plagiarism is taken very seriously. This mindset won't help the project moving forward. This is a team work and I suggest you to follow best practices while contributing. And you already have a lot of claimed issues, that you haven't solved. Pick them up first.

**Comment by samagragupta** [comment]
@akshatnitd Actually I was trying to make some changes in fragm's PR and by mistake, I push that branch.
Sorry, this would not happen again.

**Pull request closed without merging**
