### PR TITLE
Fix Footer being displayed in middle of the page and skill listing page in mobile view

### LINKED ISSUE #2200: Fix Footer being displayed in middle of the page
**Actual Behaviour**
Footer is displayed in middle of the page.

**Expected Behaviour**
Footer should stick to the bottom

**Screenshots of the issue**
Screenshot 2019-06-05 at 10 26 24 AM

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2200 
Changes: Fixed footer  being displayed in middle of the page

Demo Link: https://pr-2201-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]
Screenshot 2019-06-06 at 12 00 27 AM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
Took me quite some time to understand what the problem was and how to resolve it.

**Comment by harsh-jindal** [comment]
@fragm3 Made the changes.

**Comment by fragm3** [comment]
@akshatnitd agreed! @harsh-jindal can pick this up in the same PR or we can work this out in upcoming PR. @harsh-jindal I am still seeing the footer in places where it shouldn't be like in dashboard

**Comment by harsh-jindal** [comment]
@fragm3 @akshatnitd Please review. I have fixed the footer and skill listing page in mobile view.
Screenshot 2019-06-06 at 10 34 21 PM

**Comment by harsh-jindal** [comment]
@fragm3 I think this is still much better than what we currently have. About the line charts I will have to search a different way so that only the chart area is scrollable ( I mean without making that whole card scroll). If everything else is good than this can be merged I'll take the chart specific issue in upcoming PR.

**Comment by harsh-jindal** [comment]
@fragm3 Fixed the charts. Now the charts div is scrollable in mobile view.

**Comment by harsh-jindal** [comment]
@akshatnitd Resolved the conflicts and Footer is already removed from `SkillListing.js`. Please review

**Pull request merged**
