### PR TITLE
fixed auto scroll in preview chat

### LINKED ISSUE #3136: No auto-scrolling of the chat in the preview.
**Actual Behaviour**

The SUSI chat in the preview section of `Create a Susi skill` has no feature of auto-scrolling.

**Expected Behaviour**

It should have the feature to auto-scroll as the user continues the conversation.

**Screenshots of the issue**

final_5e00bf9dfb4b130013a8fb80_331494

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by aahel**
Fixes #3136

Changes: fixed auto scroll in preview chat

Demo Link: https://pr-3137-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
image

### CODE REVIEW

**Comment by aahel** [comment]
> Ensure that all the checks have passed in the PR and delete `yarn.lock` file from your branch.

shallow(<SkillSlideshow />); test is failing even if i remove my changes

**Comment by Dilshaad21** [comment]
Squash your commits

**Comment by aahel** [comment]
> Squash your commits

done

**Comment by aahel** [comment]
> Please mention the changes you have made in this PR.

done

**Pull request merged**
