### PR TITLE
Fixes 2961 - Addition of dark theme to homepage and dashboard

### LINKED ISSUE #2961: Dark theme not set throughout the project
**Actual Behaviour**

After setting the dark theme from settings -> theme,  the dark theme is only set in the chat and the settings section.

**Expected Behaviour**

Ideally, the dark theme should be set through the  entire project including the homepage, skills and bot related pages etc.

**Screenshots of the issue**

ThemeNotSettingAsExpected

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by AuraOfDivinity**
Fixes #2961 

Changes: This PR adds extends the dark theme from the just the setting page to the homepage and the dashboard. The colors used were chosen to match the colors that were used in the settings dark theme section.

Demo Link: http://thirsty-afternoon.surge.sh/

DarkThemeImplementation

### CODE REVIEW

**Comment by AuraOfDivinity** [comment]
@akshatnitd A couple of concerns though.
1)  I didn't manage to create a draft bot or a skill and couldn't really style the underlying components  when there is a draft skill or a bot. Would appreciate it if you could briefly explain how a draft skill/bot could be made.

2) I am also not particularly sure about the color scheme I used. Please do let me know if I should change any colors that were used or any changes that should be made in general.

Thanks in advance!

**Comment by kpulkit29** [comment]
@AuraOfDivinity I was wondering if we can work together on this one. Maybe you can continue on the PR I made.

**Comment by AuraOfDivinity** [comment]
Thanks for the feedback @akshatnitd. 
I would love to help you out @kpulkit29  is there anything specific you want me to get started with?

**Comment by kpulkit29** [comment]
@AuraOfDivinity  Would be great if you can look at the comments on #3032 

That will give you an idea.

**Pull request closed without merging**
