### PR TITLE
Added padding in admin

### LINKED ISSUE #2841: Add padding in admin
**Actual Behaviour**

No padding https://susi.ai/admin/users

**Expected Behaviour**

Add padding in https://susi.ai/admin/users

**Screenshots of the issue**

Capture

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2841

Changes: Added padding in https://susi.ai/admin/users

Demo Link: https://pr-2863-fossasia-susi-web-chat.surge.sh

### CODE REVIEW

**Comment by harsh-jindal** [comment]
@samagragupta Break the email if it is long because now the admin cannot view the actions tab without scrolling after this change.

**Comment by samagragupta** [comment]
@harsh-jindal Sorry, I could not understand what you want to explain.

**Comment by harsh-jindal** [comment]
@samagragupta Go to https://susi.ai/admin/users there you can see the actions tab without scrolling the page. Make it like that.

**Comment by samagragupta** [comment]
@harsh-jindal Its all depend on screen width. In my case, I cannot fully see the actions tab on https://susi.ai/admin/users. 
Also, we cannot see the actions tab in the Devices section.

**Comment by harsh-jindal** [comment]
@samagragupta Correct it for screen size above 13 inch. Also there is a PR opened for fixing the table in devices tab.https://github.com/fossasia/susi.ai/pull/2864

**Comment by samagragupta** [comment]
@harsh-jindal #2864 and this issue both can be done in another PR.

**Pull request closed without merging**
