### PR TITLE
Fix CSS of message footer #2312, test example for skill #2311

### LINKED ISSUE #2312: Fix CSS of message footer
**Actual Behaviour**

Not center aligned.

**Expected Behaviour**

Message Footer should be center aligned.

**Screenshots of the issue**

Screenshot 2019-06-18 at 3 16 38 AM

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2312, #2311 

Changes: 
- [x] Center align message footer #2312
- [x] Create a user message bubble while testing example

Demo Link: https://pr-2313-fossasia-susi-web-chat.surge.sh

Screenshots of the change:

Screenshot 2019-06-18 at 3 27 48 AM

Screenshot 2019-06-18 at 3 27 52 AM

Screenshot 2019-06-18 at 3 27 58 AM

Test Example bubble:

Jun-18-2019 19-09-02

### CODE REVIEW

**Comment by fragm3** [comment]
@akshatnitd tried it, it create a bubble(CDM) and then loads all the message history, then again creates a bubble(due to CDU). I think, CDU is sufficient here, as we need to wait for the messages to load.

**Comment by harsh-jindal** [comment]
@fragm3 Same for me. Please clear the browser cookies and check or check it in incognito mode. It works for me if you have chatted before clicking on test example.

**Comment by fragm3** [comment]
Missed that. Fixing it asap.

**Comment by fragm3** [comment]
@akshatnitd @harsh-jindal Made some changes, please test it now. Working fine for me after modification.

**Pull request merged**
