### PR TITLE
Fixes #2857: My Analytics Message

### LINKED ISSUE #2857: Wrong Message in My Analytics
**Actual Behaviour** 
"Your skill has not been used, make sure to improve your skill to attract more users." message is shown to users who haven't created any skills yet.

**Expected Behaviour**
 should show "You haven't created any skill yet. [Create skill Button]"

**Steps to reproduce it**
1. Create a new account 
2. Go to My Analytics Section in Dashboard.

**Screenshots of the issue**
 
Screenshot from 2019-08-15 19-42-06

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by theaayush8999**
Fixes #2857 

Changes: added message users who haven't created any skills yet

Demo Link: https://pr-2859-fossasia-susi-web-chat.surge.sh

Screenshots of the change:

Screenshot from 2019-08-15 19-42-17

### CODE REVIEW

**Comment by theaayush8999** [comment]
what are those cases where skillUsage.length === 0 and there are still some skills?

**Comment by fragm3** [comment]
@theaayush8999 try making a skill and see the My analytics section. Basically, analytics is not related to skills being made, so `Your skill has not been used, make sure to improve your skill to attract more users.` is much more apt. You could however, fix the alignment of this text.

**Comment by theaayush8999** [comment]
**I guess skillUsage state contains all skills by the Author.**

Screenshot from 2019-08-15 22-22-04

The problem was - without creating any skill, My Analytics was showing - "_Your skill has not been used, make sure to improve your skill to attract more users."_ 

My solution - if there no skill created by Author then it will show  - _"You haven't created any skill yet. "_ otherwise, it will work as before.

**Comment by theaayush8999** [comment]
Ok

**Pull request closed without merging**
