### PR TITLE
Admin: Bots

### LINKED ISSUE #2551: Admin: Add Bots Tab
The admin area has an overview of skills. However bots are missing. Please implement a tab "Bots".

Compare: https://susi.ai/admin/skills
Screenshot from 2019-07-14 19-03-37

### PR DESCRIPTION
**Pull request by harsh-jindal**
Fixes #2551 

Changes: Add Bots tab in admin

Demo Link: https://pr-2654-fossasia-susi-web-chat.surge.sh

Screenshots of the change: [Add screenshots depicting the changes.]

Screenshot 2019-07-29 at 9 53 19 PM

### CODE REVIEW

**Comment by harsh-jindal** [comment]
WIP due to delete functionality. Shall be finalised after https://github.com/fossasia/susi_server/issues/1333

**Comment by harsh-jindal** [comment]
@akshatnitd yes

**Comment by harsh-jindal** [comment]
@fragm3 You mean while opening it from my bots dashboard or from the admin page ?

**Comment by fragm3** [comment]
@harsh-jindal yes

**Comment by harsh-jindal** [comment]
@fragm3 I had deleted some test bots from the admin panel while testing this, if you find your bot missing. If the bot is not showing up on botwizard, its strange because it shows up for me. Can you go to the admin panel and try deleting `testing_1` bot ?

**Comment by fragm3** [comment]
@harsh-jindal I can't view any bot using View option, it shows `Error: Couldn't fetch skill`

**Comment by harsh-jindal** [comment]
@fragm3 I think I know why this is happening, private bots are only visible to the user who created it. Will have to make changes in the server for this. 
I guess it can be merged as the delete functionality works perfectly or shall I keep it in WIP till I fix the view issue on server?

**Comment by mariobehling** [comment]
Please resolve conflicts and add a screenshot.

**Comment by mariobehling** [comment]
Ok, thanks. We need to extend on this in follow up issues/PRs.

**Pull request merged**
