### PR TITLE
Admin: Enhance message table, remove all table scroll

### LINKED ISSUE #2785: Admin: Enhance message table
Please change the message tab https://susi.ai/admin/messages table at as follows:
* Between "Trigger" and "Email Message" add column "Subject".
* Add column "View" on the very right. By clicking on view show a pop-up with the recipient type, subject and email.

Screenshot from 2019-08-05 10-00-55

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2785, #2835

Changes: 
1. Admin: Enhance message table
2. Remove all table scrolls in admin panel

Demo Link: https://pr-2795-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 
Screenshot 2019-08-06 at 9 43 07 PM

### CODE REVIEW

**Comment by fragm3** [comment]
@akshatnitd made the changes:

Screenshot 2019-08-07 at 12 46 39 AM

**Comment by fragm3** [comment]
@mariobehling 

1. What should be the On-screen message? Should I put it to email subject, message or empty?
2. We can't put both on-screen message, email text, the table becomes too large. Show only on-screen message in the table? and email text in the popup?

**Comment by fragm3** [comment]
Made the changes:
Screenshot 2019-08-07 at 11 20 21 PM

Screenshot 2019-08-07 at 11 20 30 PM

**Comment by fragm3** [comment]
@mariobehling Except point 3, other points are done. The 3rd point is a limitation of material-table.

**Comment by fragm3** [comment]
@akshatnitd made the changes

**Comment by fragm3** [comment]
@mariobehling,
Point 1. If I set 100 rows, this makes page height huge.
Point 2, Point 4: I am using JSX for email text, how about we keep email text in view dialog as we are giving view feature for admins, the rest of column justifies what type of message is present? The scrollable table is a limitation we will have to deal with. No library provides a way to resize or transform the content of a table.

Rest points are done.

**Comment by mariobehling** [comment]
> @mariobehling,
> Point 1. If I set 100 rows, this makes page height huge.

I know what I am asking for. We need a way to see a lot of information as admins. We dont need a way for bitsized info, we need to get a good overview with lots of entries. 

> Point 2, Point 4: I am using JSX for email text, how about we keep email text in view dialog as we are giving view feature for admins, the rest of column justifies what type of message is present? The scrollable table is a limitation we will have to deal with. No library provides a way to resize or transform the content of a table.

The breaking of tables does not only happen here. It happens on many tables now and we need a way to display information over more than one line in a table. As pointed out elsewhere: It can't be that in 2019 we are not able to display more than one line in a table row using React JS.

**Comment by fragm3** [comment]
@mariobehling made the changes:

Screenshot 2019-08-13 at 3 08 19 AM

Screenshot 2019-08-13 at 3 08 34 AM

**Comment by mariobehling** [comment]
Follow up issue for remaining bugs is here: https://github.com/fossasia/susi.ai/issues/2838

Thanks.

**Pull request merged**
