### PR TITLE
Scroll bar does not disappear

### LINKED ISSUE #2530: Clicking on "Create" on the left side it results in disappearing the scroll bar of the site
When the user clicks on the blue create button, the scroll page on the right side of the screen disappears.

Screenshot from 2019-07-12 23-20-14

### PR DESCRIPTION
**Pull request by samagragupta**
Fixes #2530 

Changes: When clicked on create (or any other drop-down menu) the scroll bar disappears. 

Demo Link: https://pr-2687-fossasia-susi-web-chat.surge.sh

Or we can use this: https://material-ui.com/components/selects/#native-select

### CODE REVIEW

**Comment by samagragupta** [comment]
Or we can use this: https://material-ui.com/components/selects/#native-select

**Comment by harsh-jindal** [comment]
Your current implementation doesn't look like a good solution to the problem. Because if you click on create and then scroll the menu list also scrolls down.
Screenshot 2019-07-28 at 6 49 55 AM

**Comment by tanujvyas10** [comment]
@samagragupta Sir,the language selection icon is also distorted when i open your surge link.
langDis

**Comment by samagragupta** [comment]
So could we can use this: https://material-ui.com/components/selects/#native-select

**Comment by harsh-jindal** [comment]
@samagragupta How will that solve the problem. Even there you cannot scroll the window with select menu open.

**Comment by samagragupta** [comment]
@harsh-jindal Why there is a need to scroll the window when the select menu is open?

**Comment by harsh-jindal** [comment]
@samagragupta The screen shall not scroll. That's my point, then this PR should not be there in the first place. I dont understand what are trying to solve then ?

**Comment by samagragupta** [comment]
@harsh-jindal So according to the issue I have to show the scrollbar.

**Comment by harsh-jindal** [comment]
@samagragupta Okay. Make sure the current bug in you PR link i.e. menu list scrolling down is fixed.

**Comment by samagragupta** [comment]
I will think of any other idea and then will create a new PR.

**Pull request closed without merging**
