### PR TITLE
Fix Email Form #2710

### LINKED ISSUE #2710: Email Config not working, No test emails, Form Issues
* Clicking on dropdown form elements sidebar disappears
Screenshot from 2019-07-29 09-51-47
* SMTP Info should be below SMTP radio button
Screenshot from 2019-07-29 09-51-21
* There is no password box for SMTP mails. How could emails be sent without password?
* Test Email
   * Test Email does not work. Email is not received.
   * There is no success or unsuccessful message for "Test Mail" after clicking button. Has an email been sent or not?
* Mail Type does not make sense. Mail type is set to "Disable". Does this mean no emails are send out? Probably it should be "Mail Gateway" here. Which gateway should the system use? STMP, Sendgrid, or "Disable" for deactivating emails.
Screenshot from 2019-07-29 09-55-05
* The space of the white content area to the left-hand side and to the menu itself is not consistent across "settings subtabs" (please click on the subtabs to compare)
Screenshot from 2019-07-29 10-05-42

### PR DESCRIPTION
**Pull request by fragm3**
Fixes #2710

Changes: Fix Email Form alignment

Demo Link: https://pr-2791-fossasia-susi-web-chat.surge.sh

Screenshots of the change: 

Screenshot 2019-08-05 at 11 56 33 PM

### CODE REVIEW

**Comment by fragm3** [comment]
@harsh-jindal done

**Comment by fragm3** [comment]
@mariobehling made the changes

**Comment by fragm3** [comment]
@akshatnitd increased the font-size and width

**Comment by mariobehling** [comment]
1. It looks like you switched the content of the fields username and password. The user field actually shows the password.
2. The position of the secondary menu and the width of the white form content area is different to the standard implementation on the admin skills page. Please compare below. Please fix this in all the "admin settings subpages"

Screenshot from 2019-08-06 23-56-29

Screenshot from 2019-08-06 23-54-22

**Comment by fragm3** [comment]
@mariobehling fixed:

Screenshot 2019-08-07 at 9 35 39 AM

Screenshot 2019-08-07 at 9 35 18 AM

Screenshot 2019-08-07 at 9 35 32 AM

**Comment by fragm3** [comment]
@akshatnitd made the changes

**Pull request merged**
